### ISSUE TITLE
Problem with convention binding to decimal property

### ISSUE THREAD

**Issue by schiv** [Caliburn-Micro/Caliburn.Micro#122]
In WPF, a textbox bound to a decimal property using name convention doesn't allow inputting number followed by a decimal point.

This issue has been raised before for Silverlight:
http://caliburnmicro.codeplex.com/workitem/90

**Comment by nigel-sampson** [comment]
This problem is caused by Caliburn.Micro setting up the binding as below as well as the collision of types between the string and decimal types.

``` csharp
binding.UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged;
```

You could solve this a number of different ways.

 1. Use normal binding for those instances and don't set `UpdateSourceTrigger`.
 2. Customise the behaviour of `ConventionManager.ApplyUpdateSourceTrigger` to not change that property based on types.
3. Use a string property on the view model and have validation to enforce it's "decimalness".

Given the binding between a string and decimal types leads to some unpredictable behaviour with different inputs in different cultures on different platforms I'm hesitant to change anything in CM to deal with this.

**Comment by schiv** [comment]
Thanks. I end up using the normal binding with derived TextBox.
