### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by Laperuta** [Caliburn-Micro/Caliburn.Micro#126]
_NavigationService.NavigateToViewModel<T> fails with a NullReference Exception if the main page was initially displayed using DisplayRootViewFor<MainPage>, but all works fine if main page was displayed using DisplayRootView<MainPage>

**Comment by nigel-sampson** [comment]
Can you clarify that it's `_NavigationService` that is null and not a null reference from within `NavigateToViewModel`?

The most likely cause is that you're mixing up **View First** and **View Model First** approaches. You can read more at [Working with WinRT](http://caliburnmicro.com/documentation/windows-runtime).

Basically `DisplayRootViewFor` doesn't create a `Frame` control and doesn't set up a `NavigationService`. It simply finds the view for your view model and places it in the `Window`. In this way we're deciding on the view model first and the view follows,

`DisplayRootView` does the opposite in that it creates the `Frame` and navigates to that view, the navigation service finds the view model for that view and binds them, hence **view first*.

Most of the methods on the navigation service talk about view model, and that's mostly due to people always wanting to think in view models, regardless of the underlying approach.

The easiest way to resolve this is to use `DisplayRootView` so that the navigation service is set up and a `Frame` is your root window content.
