### ISSUE TITLE
Windows 10 Universal App Platform

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#141]
Currently a place-holder issue for commits / branches and discussion about what adding support for the new platforms will look like.

Things to consider
- [x] `Split View` - Will need to modify `BindingScope` to that we examine `SplitView.Pane` for content. Looks like `SplitView` doesn't inherit from `ContentControl` so even more work here.
- [x] API unification - Consider the impacts of unifying the Windows 8.1 and Windows Phone 8.1 APIs.
- [x] Compiled data binding - What impact will this have? Need to find out if we can detected these compiled bindings in some way. `x:Bind` won't be able to be detected, will need to publish guidance of using `x:Bind` in partnership with conventions.
- [x] Device Family folders - Does this effect view location?
- [x] Behaviours SDK is now part of platform
- [ ] ~~Can see some Validation properties on Control, can we use them?~~
- [x] Does the `ISettingsService` make sense now? It's marked as obsolete so won't have code migrated.
- [ ] ~~What do we need to do to support `KeyAccelerator`?~~
- [x] Need to take into account new `SystemNavigationManager`. ([source](http://www.sharpgis.net/post/2015/05/21/Displaying-a-backbutton-in-your-app-window))
- [x] There's a new xaml page template that doesn't have a code behind, it looks like it's not doing a very good job of generating / maintaining the class based on x:View.
- [x] Back button support.
- [x] Remove project.lock.json
- [x] Sample app

**Comment by unt1tled** [comment]
Cool. Was just going to ask about this.

**Comment by nigel-sampson** [comment]
Having some issues with my Windows 10 VM's at the moment but from what I can tell so far the Windows 8.1 version of CM should continue to work with no problems. 

The only issues that may arise are when the CM API surface area between Windows 8.1 and Windows Phone 8.1 differ then these features may not be available right now. I think this is only limited to `NavigationService.BackPressed`.

Will add to this when I know more.

**Comment by unt1tled** [comment]
I was able to add the reference to the UAP project no problem, but I the bootstrapper from the platforms namespace didn't carry over. I started creating a new platform project based on UAP, and indeed, most of the 8.1 stuff are one to one, with the exception a few gotchas.

**Comment by nigel-sampson** [comment]
Finally got everything up and running, quick test indicates that for the most part the Windows 8.1 assemblies run against Windows 10 UAP. The only change to really deal with is that the nuget package adds a reference to the now non existant Behaviours SDK. What you need to do is remove that reference and manually add a reference to those dlls from somewhere.

**Comment by unt1tled** [comment]
Thanks for the update Nigel! I'm just having trouble using things like Autofac because BootstrapperBase isn't found after referencing Caliburn.Micro. Are you finding this to be the case?

**Comment by nigel-sampson** [comment]
I didn't check WPF or Windows Phone Silverlight, will have a quick check soon.

**Comment by unt1tled** [comment]
Oops, forgot to mention its for a UAP project.

**Comment by nigel-sampson** [comment]
Ah of course, I'm an idiot. UAP projects work pretty much the same as Windows 8.1 / Windows Phone 8.1. `Bootstrapper` doesn't exist for those platform, instead we use `CaliburnApplication`. Functionally they're the same, just in different places. Check out the [documentation](http://caliburnmicro.com/documentation/windows-runtime) on how those platforms work.

Technically the reason is that in WPF and Silverlight you could attach to the applications lifecycle via events, in WinRT and now UAP it's all done via method overrides.

**Comment by unt1tled** [comment]
Ah. My mistake actually. I initially had it per the documentation you provided, but then assumed I was doing something wrong when I got "CaliburnApplication is not usable as an object element because it is not public or does not define a public parameterless constructor or a type converter." in my App.xaml

**Comment by nigel-sampson** [comment]
I got that error but after a build it went way.

**Comment by unt1tled** [comment]
Hmm.. That's where I'm stuck at now. I'll continue to mess around with it and see if I discover any fixes.

**Comment by nigel-sampson** [comment]
I've pushed up an initial project, right now just a consolidation of the Windows Phone 8.1 and Windows 8.1 API surface area. You'll see things like `INavigationService.BackPressed` now, however won't ever fire on platforms that don't support it.

**Comment by unt1tled** [comment]
Got it to work. Somehow the Build Action on my App.xaml wasn't set to ApplicationDefinition  Thanks for your assistance. I'll try out the new uap commits.

**Comment by renemaat** [comment]
I have been trying the new UAP out a bit and like it so far. I do have an issue with the splitview in combination with the INavigationService, maybe I'm just looking at it the wrong way. The app that I'm creating has the splitview to create a hamburger menu, from that menu you can select a menuitem and from that point you can navigate deeper into the app. We want to have the menu available on each page and be able to navigate back through the backstack. 
The problem that I have is that to get this working the navigation service is registered on the rootframe, and not on the frame that is in the splitview.content. I do have it working but its not very clean. 

In the Configure I register the navigation service with the root frame because there are a few steps before the actual main page. I have created a Shell view that has no view model, this shell has the splitview. In this shell I remove and register the navigation service again and add the backbutton handling. The menu click events are handled from the code behind but from there I can navigate with the new navigation service.
I'm not sure if there can be any sort of support for this scenario being added to CM. I can provide samples and other help if needed. Thanks in advance.

**Comment by mvermef** [comment]
Settings can be tossed in UAP for windows 10 branch... Since Settings was reliant on Charms Bar, well that is all completely gone, therefore deprecated.

**Comment by mvermef** [comment]
Not to beat a dead horse but they made significant changes to the project for UWPs, made them more like ASP.NET projects with dependencies resolved via project.json, from Nuget. Suspect more under the hood changes occurred with the over all xaml framework

**Comment by nigel-sampson** [comment]
Yup it's on my mind too, the current plan is to

1. Get the official tools once released.
2. Have the obvious stuff up to date and working.
3. Merge it into 3.0.0
4. Get a new beta out for discussion / experimentation.

**Comment by nigel-sampson** [comment]
Regarding the nuget package stuff, I'm working through this on some discussion lists. Given that the package needs to support older versions and different platforms we may not be able to jump onto the new package format yet.

**Comment by mvermef** [comment]
Ironically it pulls in the latest version of CM without having to work to hard to make it work.  I will have more shortly.  Main desktop is struggling with getting VS2015 on it.  Blowing out install of insider install of W10...  To many issues with over the top installs :(

**Comment by nigel-sampson** [comment]
Yeah Windows 10 will happily use the Windows 8.1 version of CM with no hassles.  Most of what needs to be done is seeing if there any new controls we want to add conventions for or add rules to `BindingScope`.

There's a bit of an API convergence in our Win 8.1 and Win Phone 8.1 API's that will now be handled with feature discovery.

**Comment by MichaelGulliver** [comment]
Hi guys! I'm successfully using Caliburn Micro with final SDK in Universal!
I changed conditional symbol WINDOWS_UAP to WINDOWS_UWP and then replaced it all over the code.
Also I found a problem on Platform ConventionManager at line 386: missiing condition  "&& !WINDOWS_UWP" makes my app crash!

Thanks for your job, bye !!!

**Comment by nigel-sampson** [comment]
Glad to hear you've had some success.

Finally able to sit down and work with the new tools and running into some issues mostly around the new 'project.json'.

The issue is around the way we have all the projects in the sample folder for portable and platform. No real concerns before and it's an easy way to share files between projects. `packages.config` was an issue but solved by the ability to prefix the file with the project name.

This doesn't seem to work however with `project.json` which being just present in the folder breaks the build of all of the platform projects.

The potential solution may be to shift to using shared projects with platform specific heads in their own folders. Not to difficult, but time consuming. Talking to MS at the moment to see if this is the recommended approach.

**Comment by nigel-sampson** [comment]
Confirmed from Microsoft that shared projects are the recommended approach, so we'll need to do a large scale restructure :-1:

**Comment by mvermef** [comment]
Wired up based on sample.. Lot more to look at but will have to remember to use ```For<>``` (new navhelper) with the navigation service.  Can cause some weird behavior with ```_navService.Navigate<MainViewModel>()```  it will cause some corruption errors to develop.  Also sequence of events with the Load method via attach has to be respected so loading in OnActivate has bad results if you trying to navigate to a view at load, thinking that this is where you wanted to show the next screen at startup.  Which is no longer correct due to the fact we are placing Frame in the content of the SplitView (which is pretty damn neat and clean)...  I also put the SystemNavigationManager stuff partially in that SetupNavigation method as well as part of the event for Navigated to show the Back button.  Going back works great with that button code for the SystemNavigationManager

**Comment by nigel-sampson** [comment]
Can you elaborate on the corruption errors you mention as I haven't seen anything like this yet.

Yeah the lifecycle isn't ideal here, you can actually set a default view using `SourcePageType` on the `WebView` ([sample](https://github.com/nigel-sampson/xbox-media-remote/blob/master/XboxMediaRemote.App/Views/MediaHubView.xaml#L97)).

Ancedotally I've found if you're navigating in your `OnInitialize` or `OnActivate` something has gone a bit wrong as you end up descending a bit of spiral in manipulating history.

The sample could certainly use some more clean up in terms of patterns, but at the moment just testing it works.

**Comment by mvermef** [comment]
Well OnInitialize and OnActivate will not be used for NavigationService in this sense now since NavigationService will be null till SetupNavigation has been reached.  Which it will not be in the case of OnInit / OnActivate since they are both hit before the SetupNavigation is called due to the nature of the layout.  The navigation pattern in this case is detoured till after _navService local variable is assigned the relevant instantiation during the SetupNavigation.  While it could catch someone by surprise when they first run it, by no means would it be a head trip to bad.

This is all stems from normal usage of INavigationService as an injection not from the standpoint of actually making it available for the reset of the application till after the first ShellViewModel for example makes it available (normal available immediately following Configure() in App.cs.xaml

**Comment by nigel-sampson** [comment]
Ok, thought there was another underlying issue I was missing.

You can still use `INavigationService` with constructor injection in every view model except for `ShellViewModel`, will most likely expand on this in a tutorial / blog post.

**Comment by llvk** [comment]
Can anybody explain me why ViewModel is not binded to View when I navigating with _navigationService.For<ViewModel>().Navigate() from ShellViewModel with a SplitView + Frame?
Frame shows me the View but Caliburn does not even call constructor of ViewModel.

P.S. I have the HelloUWP sample with little changes.

**Comment by mvermef** [comment]
Probably due to a naming error for the namespace or view to viewmodel or a combination of both.

 There are issues associated with this scenario with resume and restore at present...

-----Original Message-----

**Comment by nigel-sampson** [comment]
As @mvermef said, this is typically caused the one of two different things.

- A naming error where the framework cannot locate the corresponding view model for the view. For this I'd double check that names match the conventions.
- The view model is not registered with the container. You can see in `App.xaml.cs` where this is happening in the HelloUWP sample.

**Comment by llvk** [comment]
I have forgotten set Frame.DataConext to {x:Null}, so that's my fault.

Sorry for misinformation.

**Comment by nigel-sampson** [comment]
No worries, glad it's resolved.

**Comment by nigel-sampson** [comment]
Done in `3.0.0`, how did I miss this?
