### ISSUE TITLE
Inconsistent Code Signing

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#155]
Only some of the assemblies are signed, all or none should be signed.

**Comment by tibel** [comment]
If I remember correctly the assemblies are strong named on all platforms that support strong naming.

**Comment by nigel-sampson** [comment]
Thanks, will double check this soon just to make sure I didn't miss one when creating all the damn projects.

**Comment by nigel-sampson** [comment]
So current only the Windows 8 projects are unsigned due to Callisto being unsigned. Will leave this open as a reminder when the xamarin and windows 10 branches come onto master.

**Comment by nigel-sampson** [comment]
Can't sign the xamarin forms assembly due to no signing from xamarin, just need to check windows 10 builds.

**Comment by nigel-sampson** [comment]
It's about as consistent as it's going to be.

**Comment by kayle** [comment]
@nigel-sampson I'm in the midst of converting an old WP7 app to a Win10 UWP app and inconsistently see an error in the designer due to Microsoft.Xaml.Behaviors.Uwp.Managed 1.1.0 being unsigned now (https://github.com/Microsoft/XamlBehaviors/pull/85). Would it therefore be correct to stop signing Caliburn.Micro.Platform.UWP as well now?

**Comment by nigel-sampson** [comment]
Yeah I think it's something to revisit. The general view of the community is seeing signed open source as something that's not wanted. I'd probably leave off till `4.0.0` though as it'll be a breaking change.
