### ISSUE TITLE
BindableCollection and sealed methods

### ISSUE THREAD

**Issue by pawelpabich** [Caliburn-Micro/Caliburn.Micro#180]
Hi,

Is there a reason that some of the overriden methods are marked as sealed? I would like to  wrap them with my custom behavior and currently this is impossible

**Comment by nigel-sampson** [comment]
I'm not 100% sure as this one done before I started on the project, looking over the code I would assume the reason is to ensure things are being properly dispatched to the UI thread.

However after looking at the code for every sealed method there's a corresponding virtual `*Base* method that can be overrriden.

This way the sealed `RemoveItem` ensures for instance that `RemoveItemBase` is on the UI thread, while still leaving a place for you to insert your wrapping.

**Comment by pawelpabich** [comment]
Thanks, missed that.
