### ISSUE TITLE
SplitView implementation using Caliburn.Micro and Bindings problem

### ISSUE THREAD

**Issue by Yurijj** [Caliburn-Micro/Caliburn.Micro#185]
Is it a possible to provide a code sample how to use SplitView from Windows-XAML/201505-MVA/SplitView: https://github.com/Windows-XAML/201505-MVA/tree/master/SplitView with Bindings and CaliburnMicroApp?

Have a problem to use Binding because of RootFrame, Main Page content etc. More over, looks like we need a wrapper for NavigationService as well.

So, just want to ask a sample to work with:
UAP10 + Caliburn.Micro + SplitView + Several Views and ViewModels with working bindings.

Thanks.

**Comment by nigel-sampson** [comment]
It's certainly possible, there's currently a [branch of Caliburn.Micro](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/windows-10) that adds Windows 10 / UWP support.

This includes drilling into the SplitView for conventions / bindings.

I'm currently unable to distribute this as a binary since we don't get have nuget identifier for UWP so you'll need to compile the source.
