### ISSUE TITLE
WinRT and OnActivate/OnDeactivate methods

### ISSUE THREAD

**Issue by belyansky** [Caliburn-Micro/Caliburn.Micro#187]
I've just made an unexpected discovery that in Windows Runtime `Frame.OnNavigating` and `Frame.OnNavigated` events don't fire if a user goes away from an app by hitting `Win` button or by hitting `Back` button from the first page. They also don't fire when the app is resumed. As the result `OnActivate` and `OnDeactivate` methods of the active view model (screen) also don't work in this situation. And I can't properly update data of the view model like it was with Windows Phone Silverlight.

So what is a right way for updating data of the view model with help of Caliburn.Micro in this scenario?

**Comment by belyansky** [comment]
There are also `Application.Resuming` and `Application.Suspending` events, `Page.OnNavigatedTo` and `Page.OnNavigatedFrom` methods (which are called in process of suspension or resuption in pair with `Frame.GetNavigationState` or `Frame.SetNavigationState` only), but I can't figure out how to combine them in some elegant and MVVM-friendly solution.

**Comment by sshumakov** [comment]
Hello,

I have solution for Caliburn integration with SuspensionManager. Basically, you will have Save and Restore methods on state dependent view models.

Where do you want me to share this solution?

**Comment by belyansky** [comment]
@sshumakov In fact I haven't any specific preferences. Use what is comfortable for you. But maybe gist.github.com will be the right place.

**Comment by mvermef** [comment]
I would just post a pull request with changes and see if it gets accepted.  I sure it will also depends on the structure of changes and how you are doing the integration

**Comment by nigel-sampson** [comment]
Some of this is discussed in #95, `INavigationService` and `FrameAdapter` already support `Frame.GetNavigationState` and `Frame.SetNavigationState` to help the preservation of frame history over app sessions.

I've also sometimes had to work with `Window.VisibilityChanged` to add some features in too.

Often I do this by globally subscribing to the event, or method override in *App.xaml.cs* and then publishing something via the `EventAggregator` to any interested view models.

@sshumakov in terms of a pull request, I guess it really depends on how it's structured, anything that changes stuff in core portable assemblies would most likely not be accepted since we try to keep that platform agnostic.

Issues here also include how we discover which view models want to save state. Most solutions including `SuspensionManager` assume the `Frame` wraps the entire application and there isn't a different root view / conductor. That scenario seems more likely now with the Windows 10 Split View control / navigation pattern.
