### ISSUE TITLE
Improving samples

### ISSUE THREAD

**Issue by igorkulman** [Caliburn-Micro/Caliburn.Micro#202]
I use Caliburn in Windows Phone 8 and 8.1 XAML project and I started with the samples you provide. Now I want to create a WPF project and looking for a sample to get me stared. Doing this I realized the sample structure and samples could be improved. 

I would suggest a few things
- Create starter samples for the supported platforms, just something basic with the setup, 2 screens and navigation between them (I could not find anything like this for Caliburn 2.0 and WPF). 
- Organize the samples by platform. When looking for a WPF sample I had to open nearly all of the samples to find out there are Silverlight based, because the platform is not specified in the name or anywhere (except for WP, WINRT). I know that the concepts EventAggregator, etc. are not platform specific, but at least the starter samples should be organized by platform. If someone new comes to the repo and want to start with Caliburn, they would start with a starter sample according to the required platform and then move to to other independent concepts.

**Comment by nigel-sampson** [comment]
Yeah it's definitely something that's been on the back of my mind, I raised #156 as a bit of a place holder issue. I think I'll close that one down and keep the discussion here.

Samples usually come in three different flavours.

- How to get started on each platform, nothing complex just a kind of finished project after going through a normal setup process. There is currently a *Start* nuget package, but it doesn't work well on the new platforms, this could be replaced by project templates distributed by the Visual Studio gallery as well. My instinct says having a sample project in the repository which is used to build the project template is probably the best way.
- Platform unspecific features such as Conductors, View Model Location & Event Aggregator. These can be done in little samples (like they are right now), or one larger project such as the HelloRT sample which was used to test the port to WinRT. I think the former is better otherwise people get confused where one feature ends and another beings.
- Platform specific stuff such as Navigation Service, Window Manager, Sharing Service. A lot of the above applies to this as well. Smaller projects are better here.

Great suggestions, it's kicked off me thinking about it more a bit of a plan of action, now to find the the time.

**Comment by nigel-sampson** [comment]
This has been completed.
