### ISSUE TITLE
Windows 10 failed to create instance of Interface when I use IoC

### ISSUE THREAD

**Issue by RikardoPons** [Caliburn-Micro/Caliburn.Micro#206]
Hello I'm playing with Caliburn micro 3.0 alpha 
I configured my project for using caliburn and works fine!.

But now I created a service with separated Assemblies this service has a provider, the order is like this:.
MyProject.Provider
   Provider.cs
MyProject.Service
  Service.cs
MyProject.Interface
IService.cs

I added the references to my project of Windows 10 :
MyProject.Service
MyProject.IService
I Added this service in the Configure method as Singleton:

container.Singleton< IService,Service >();

In the constructor of my ViewModel I added just this line of code:

var myService= IoC.Get< IService >();

UPDATE:
I override the SelectAssemblies method to add the assembly of my Service:

  assemblies.Add(typeof(MyService).GetTypeInfo().Assembly);

and throws an Exception

An exception of type 'System.MissingMethodException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: Cannot create an instance of an interface.

I solved this issue overriding GetInstance method

    protected override object GetInstance(Type service, string key)
        {
            var instance = container.GetInstance(service, key);
            if (instance != null)
                return instance;
            throw new InvalidOperationException("Could not locate any instances.");

        }
I think is a bug of Caliburn Micro.
I know is an alpha version.
I just want to report this Issue.

Best Regards.

**Comment by mvermef** [comment]
Did you override SelectedAssembly property?

**Comment by RikardoPons** [comment]
Yes, I will update my post.

**Comment by nigel-sampson** [comment]
`SelectAssemblies` shouldn't be required here, it's used for the `ViewLocator` and `ViewModelLocator` when trying to find matching types.

I've been testing the Windows 10 pretty heavily lately and haven't run into this problem.

On further reading are you saying you resolved the issue with the override on `GetInstance`? If so this is by design as the framework does not come with the container already wired in, a lot of people already have a container framework of choice such as Unity or Ninject.

Therefore whenever you use a container you should be overriding `GetInstance` `GetAllInstances` and `BuildUp` of `CaliburnApplication` to use your container.
