### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by NicolasHumann** [Caliburn-Micro/Caliburn.Micro#21]
Did you plan a support of Xamarin, like did MVVM Cross ?

Thx

**Comment by Petoj87** [comment]
any news on this?

**Comment by bitbonk** [comment]
Prism started supporting Xamarin.Forms: https://github.com/PrismLibrary/Prism.Mvvm/tree/master/Source/Prism.Mvvm.Forms

**Comment by Petoj87** [comment]
MVVM Light also seems to support it, but to add some thing constructive Xamarin.Forms uses [BindableObject](http://iosapi.xamarin.com/index.aspx?link=T%3AXamarin.Forms.BindableObject) instead of DependencyObject and [BindableProperty](http://iosapi.xamarin.com/?link=T%3aXamarin.Forms.BindableProperty) instead of DependencyProperty. also ui controls dont use INofityPropertyChanged they instead use [TextChanged](http://androidapi.xamarin.com/?link=E%3aAndroid.Widget.TextView.TextChanged) or [CheckedChange (Android)](http://androidapi.xamarin.com/index.aspx?link=E%3AAndroid.Widget.RadioGroup.CheckedChange), [ValueChanged (iOS)](http://iosapi.xamarin.com/?link=E%3aUIKit.UIControl.ValueChanged).

[Source](http://blog.galasoft.ch/posts/2015/03/solving-the-event-not-found-issue-in-xamarin-mvvmlight-binding-and-commanding/)
