### ISSUE TITLE
How to get instance of ViewModel registered as PerRequest in OnSuspending

### ISSUE THREAD

**Issue by xlazom00** [Caliburn-Micro/Caliburn.Micro#210]
My application in universal app for WP8 and Windows 
And I am looking for right way how to save data in OnSuspending
I have ViewModel registered as PerRequest 
But I need to save some data from ViewModel in OnSuspending
But all metohods from SimpleContainer create new instance of ViewModel
So any advice ?

**Comment by nigel-sampson** [comment]
There's no built in way to get the "current view model" because depending on your application that can 
mean a lot of different things.

A simple hack is that you have access to the `RootFrame.Content` which typically gives you the current view (assuming a standard WP8 app). Casting this to `FrameworkElement` will give you the view model as the `DataContext`.
