### ISSUE TITLE
Adding or removing nodes from TreeView manually

### ISSUE THREAD

**Issue by OfekA** [Caliburn-Micro/Caliburn.Micro#215]
Is it possible to remove and add (basically manipulate) nodes manually from the viewmodel? If yes, how?

Thanks,
Ofek

**Comment by nigel-sampson** [comment]
This is a bit of an open ended question (probably best for Stack Overflow since you'll get better visibility).

You can bind a tree of view models to a tree view in xaml in WPF (I'm assuming this is the platform). There's nothing Caliburn specific in this so you should be able to find some articles on how to do this.

Once the binding is set up then simply manipulating the view model tree will update the view tree.
