### ISSUE TITLE
multi frame

### ISSUE THREAD

**Issue by zhengbomo** [Caliburn-Micro/Caliburn.Micro#223]
my uwp app had contains multi frame in one page, how to use INavigationService for it, is there some demo for the case

**Comment by mvermef** [comment]
when you say Frames are you implying `<Frame />`

**Comment by nigel-sampson** [comment]
Each `Frame` could be wrapped with it's own `FrameAdapater` and registered with the container. Take a look at the UWP sample on the 3.0.0 branch for how to do this.

Since you'll be doing this twice I assume you'll want both navigation services registered with the container. In this case you'll need some way to distinguish them so that each child view model gets the correct navigation service.

Some containers such as Ninject let you customise the injection behaviour quite considerably which is definitely a good approach. If however you want to stick with `SimpleContainer` then you'll probably need to create your own interfaces inheriting `INavigationService` and register those types with the container.
