### ISSUE TITLE
Template10 and Caliburn micro

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#234]
The Template10 library (https://github.com/Windows-XAML/Template10) contains interesting controls  and grows more each days.
I would like to use it in a project with caliburn micro. Problem is they both use a bootstrapper.
Is there any way to use both libraries? Anyone done it ?

**Comment by mvermef** [comment]
Jerry's done some amazing work there it really is a self contained mvvm template for using the splitview.  It might take alot tweaking or you may want to go with development of CM only template.  One thing to notice is the extensive use of async, which we don't do yet.

-----Original Message-----

**Comment by nigel-sampson** [comment]
Your approach would differ quite a bit depending on what you wanted to use from Template 10, there wouldn't be anything stopping you using the Template 10 project and not the template in order to use the controls and some of the services.

Obviously there's a lot of overlap in terms of functionality so working out which pieces of which you want to use will be time consuming as well making sure they work together,

**Comment by lploumen** [comment]
OK I understand. I was mostly interested by the HamburgerMenu control from Template10. I think I'll get the .xaml and .cs from the project and modify it or take another one.
Thank you for the replies.

**Comment by wstaelens** [comment]
interested in this also as Template10 helps a lot when starting with UWP.

**Comment by nigel-sampson** [comment]
It really depends on what parts of Template 10 you want to use, there's a lot of overlap so you'll also want to determine which parts of which and so on. 

Using the controls, converters and behaviors will be easier due to (hopefully less dependencies on the framework). 

There's going to be no cut and dried answer for this short of "it depends".

**Comment by lploumen** [comment]
From my side, I would like to use their HamburgerMenu which looks cool. If I want to use it, I need a navigation service which is built by the bootstrapper.
Isn't the main concern that they both use Bootstrappers ?
If Template10 or CM could be use without it (or from another way), wouldn't this issue be solved ?
And I'm not saying it is easy...

**Comment by nigel-sampson** [comment]
You've got a few options for using something like `HamburgerMenu`.

1. Writing an adapter from Caliburn.Micro's navigation service to T10's. You can then plug the adapter into the menu.
2. Taking the code for the menu and rewrite to the use Caliburn.Micro's navigation service.
