### ISSUE TITLE
Xamarin.Forms: DisplayAlert throws exception using EventAggregator.PublishOnMain()

### ISSUE THREAD

**Issue by janniksam** [Caliburn-Micro/Caliburn.Micro#244]
When I use deep in my communication-class:

    m_eventAggregator.PublishOnCurrentThread(message);

and subscribe to it in my (pseudo)viewmodel like that:

    public async void Handle(LoginResponseMessage message)
    {
        if (message.LoginStatus == LoginStatus.UserNotFound)
        {
            await ShowValidationWarning("User not found", "The user was not found in our database");
        }
        else if (message.LoginStatus == LoginStatus.WrongPassword)
        {
            await ShowValidationWarning("Wrong password", "Please reenter your password");
        }
    }

ShowValidationWarning looks like this:

        private async Task ShowValidationWarning(string title, string message)
        {
            if (m_showAlertAction != null)
            {
                await m_showAlertAction(title, message, "OK");
            }
        }

and the action is filled by the view here (DisplayAlert is set to the action)

        [ImportingConstructor]
        public LoginView(LoginViewModel viewModel)
        {
            InitializeComponent();
            m_viewModel = viewModel;
            m_viewModel.Init(DisplayAlert);

            BindingContext = m_viewModel;
        }

Why is this giving me a exception? I thought, its running on the UI thread, isnt it?

**Comment by nigel-sampson** [comment]
What's the exception details you're seeing?

**Comment by janniksam** [comment]
{Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 \n  at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod) [0x00063] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:178 \n  at Android.App.AlertDialog+Builder.Create () [0x00043] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.AlertDialog.cs:178 \n  at Xamarin.Forms.Platform.Android.FormsApplicationActivity.<InternalSetPage>b__20_1 (Xamarin.Forms.Page sender, Xamarin.Forms.AlertArguments arguments) [0x00013] in <filename unknown>:0 \n  at Xamarin.Forms.MessagingCenter+<>c__DisplayClass1_0`2[Xamarin.Forms.Page,Xamarin.Forms.AlertArguments].<Subscribe>b__0 (System.Object sender, System.Object args) [0x00027] in <filename unknown>:0 \n  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006f] in <filename unknown>:0 \n  at Xamarin.Forms.MessagingCenter.Send[Page,AlertArguments] (Xamarin.Forms.Page sender, System.String message, Xamarin.Forms.AlertArguments args) [0x00013] in <filename unknown>:0 \n  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String accept, System.String cancel) [0x0001f] in <filename unknown>:0 \n  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String cancel) [0x00000] in <filename unknown>:0 \n  at Project.ViewModels.LoginViewModel+<ShowValidationWarning>d__26.MoveNext () [0x0002e] in E:\ProjectPath\ViewModels\LoginViewModel.cs:123 \n  --- End of managed exception stack trace ---\njava.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()\n\tat android.os.Handler.<init>(Handler.java:200)\n\tat android.os.Handler.<init>(Handler.java:114)\n\tat android.app.Dialog.<init>(Dialog.java:108)\n\tat android.app.AlertDialog.<init>(AlertDialog.java:125)\n\tat android.app.AlertDialog$Builder.create(AlertDialog.java:973)\n}

This sounds kinda interesting:
Can't create handler inside thread that has not called Looper.prepare()

**Comment by nigel-sampson** [comment]
That does look like an issue with it not being on the UI thread.

Can I confirm you're using `CaliburnApplication` as in [this sample](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3.0.0/samples/Hello.Forms/Hello.Forms/Hello.Forms.Droid/Application.cs)?

This sets the up the `AndroidPlatformProvider` that posts things on to the UI thread.

**Comment by janniksam** [comment]
Actually I do not derive from Caliburn.Application. The only thing I was going to use from your Framework (for now) is the EventAggregato.

So, I have to derive from CaliburnApplication? Anything else like initializing something? Again, for now I just need the eventaggregator.

I guess, there should be an exception thrown, when caliburn tries to publish on UI, when it's not set up to do it on main thread, can't be right to continue publishing but using a different thread, can it?

**Comment by janniksam** [comment]
Alright, alright, I was curious about how the MVVM things works in the mobile world.

Just seeing this like of code:

         public LoginViewModel(INavigationService navigationService) 
         { 
             this.navigationService = navigationService; 
         } 

Without trying out (I am not home at the Moment) the sample. Is it possible to dependency inject other things? I dont see any ImportingConstructor-Attribute, so how would this look like, when I need to dependency inject the IMyClass Interface? At the moment I use the Microsoft.Composition framework to inject things into my classes, but excactly does it work with caliburn micro in the mobile world?

**Comment by mvermef** [comment]
Yes you can inject anything you deem necessary.  For mobile development I think you will find that relying on MEF (aka Composition) is probably a bad idea since the design usually relies on reflection.  Full implementation might not be available in all platforms.   Most of my mobile/non-mobile development I have actually dropped MEF in favor of the built-in container SimpleContainer which is leveraged out of the box.  If you want to go another direct for containers, there a countless flavors to choose from.  Another reason was MEF didn't play well with open generics, this may be have been solved in v2.  On top of that you don't have to deal with MEF's b.s. ambiguous errors, let alone locate them.  

    //Simple Container
    SimpleContainer container = new SimpleContainer();
    container.PerRequest<AircraftViewModel>()
                   .PerRequest<IAircraftContext, AircraftContext>()
                   .Instance<SettingsViewModel>();

    ///.... brevity... refer to samples for BuildUp()/Get()/GetAll()

    ///AircraftViewModel
    public class AircraftViewModel{
        private readonly IAircraftContext _context;
        private readonly IEventAggregator _events; 
        public AircraftViewModel(IAircraftContext context, IEventAggregator events){
              _context = context;
             _events = events;
        }
    }

**Comment by janniksam** [comment]
Thanks for the reply :)

So, basically what you're trying to say is, when I will implement the CaliburnApplication class properly like in the sample, I can just add another parameter like this?

     public LoginViewModel(INavigationService navigationService, IMyClass myclass) 
     { 
         this.navigationService = navigationService; 
     } 

How do I export the class though? Do I have to declare every single type in my CaliburnApplication by creating an instance and adding it to the Container? Or are the similar things like the [Export]-Attribute ín MEF?

**Comment by janniksam** [comment]
And I have another question:

I sucessfully implemented the whole architecture you used in the sample now and I see my view and also have my viewmodel being called with cal:attach(). The only thing thats not working is OnViewLoaded()...

Any idea why that method isn't being called by Caliburn.Micro? The OnViewAttached is being called, but not the OnViewLoaded override...

**Comment by nigel-sampson** [comment]
A lot to cover but will do my best.

My default we use `DefaultPlatformProvider` that basically does as little as possible. It's tempting to do as you say and replace this with one that throws up an exception rather than fail in unexpected ways.

You can see the the start up code that `CaliburnApplication` provides here in [Initialize](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3.0.0/src/Caliburn.Micro.Platform/android/CaliburnApplication.cs#L80) and [StartRuntime](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3.0.0/src/Caliburn.Micro.Platform/android/CaliburnApplication.cs#L46).  If you didn't want to inherit `CaliburnApplication` you need to call a subset of this code yourself appropriate to what you're using.

Regarding inversion of control, the framework is agnostic to any particular dependency injection framework so you're free to use MEF, Ninject, AutoFac you choose. Out of the box we ship one named SimpleContainer to help things long 

As @mvermef showed in the above comment you're not actually creating new instances of the objects to register their types with the container, just referring to the type directly.

A lot of the `ViewAttached` / `ViewLoaded` code isn't yet working for Xamarin Android, we're still working on what makes sense here on Android.

**Comment by nigel-sampson** [comment]
Raising #248 as possibility to help resolve this.
