### ISSUE TITLE
Support async methods in Screen, IActivate etc

### ISSUE THREAD

**Issue by ZoolWay** [Caliburn-Micro/Caliburn.Micro#245]
You can override `Screen`s `OnInitialize()` with the `async` keyword and use `await` within. By design of async-await the Activate method of Screen will continue. Therefore, while `OnInitialize()` is not completed yet, `OnActivate()` is already executed.

There are quite common cases where you would not like to have `OnActivate()` to run before `OnInitialize()` is completed. For that it is necessary to await `OnInitialize()` and every child task within there should be created with `TaskCreationOptions.AttachedToParent` (compare child tasks vs. nested tasks).

In your ViewModel inheriting from Screen you could then do:

``` c#
protected async override Task OnInitialize()
{
    await Task.Factory.StartNew(() =>
    {
        this.configuration.Load(Properties.Settings.Default);
    }, TaskCreationOptions.AttachedToParent);
}
```

I have checked this with a copy of `Screen` as `ScreenAwaitingInit` which implements two things different (origin source from 1.5.2 but adoptable):

``` c#
async void IActivate.Activate()
{
    if (this.IsActive)
        return;
    bool flag = false;
    if (!this.IsInitialized)
    {
        this.IsInitialized = flag = true;
        await this.OnInitialize();
    }
    this.IsActive = true;
    ScreenAwaitingInit.Log.Info("Activating {0}.", (object)this);
    this.OnActivate();
    this.Activated((object)this, new ActivationEventArgs()
    {
        WasInitialized = flag
    });
}

protected async virtual Task OnInitialize()
{
}
```

This is to show what my problem is and what I am after.

Maybe it is possible to support both ways in one `Screen` implementation or you could provide two `Screen` classes (inheriting most stuff from `ScreenBase`) either implementing one behaviour. But it would be great. I would even try to contribute a pull request if I would know what type of solution would be preferred.

**Comment by nigel-sampson** [comment]
Thanks, it's something that's been on my radar for a while, introducing async / await into the code base is going to be a reasonably large change because we still need to support platforms where it isn't.

**Comment by ZoolWay** [comment]
A way to go here might be to make several methods virtual and fields protected. So you could inherit from `Screen` (etc) and provide variants for platforms where async/await is available. Would even make my workaround easier as it would no longer require to copy the whole `Screen` class source.

**Comment by macsux** [comment]
Shouldn't IsInitialized and IsActive flags be set **after** the invocation of OnInitialize and OnActivate methods respectively, as they are the ones that will contain the logic relevant to each state, while the flags signify completion of such actions?

**Comment by nigel-sampson** [comment]
Depends on how you think about the code, the `OnX` methods can be viewed as callbacks for the main method so the view model is already active when the callback is called.

However can totally see your point of view and if I was writing this from scratch I'd probably do it that way. 

For something like this though changing that behavior would be a significant breaking change and probably wouldn't change it for little gain.

**Comment by ZoolWay** [comment]
While I can also see macsux's point I'd like to add that my main problem was that the `OnActivate()` call will be executed before `OnInitialize()` has complete if the later one uses async/await. That can be a challenge for the lifecycle and you would have to implement your own additional flag or do like with my workaround to have an `OnInitialize()` which is awaited before `OnActivate()` is called.

What kind of behaviour have you in mind for 4.0.0 nigel?

**Comment by nigel-sampson** [comment]
Yup, sorry wasn't clear here. 

Fully intend to add support for an async methods, would like to do this in a way that's not a major breaking change but hard to see how to do that effectively. I'd like to avoid having both `Screen` and `AsyncScreen`, but not also forcing people to use async when they don't need to.

The `wontfix` above was simply about having the `IsActive` flag set to true before `OnActivate` is called.

**Comment by PatrickKunz** [comment]
It would be great to have `async virtual Task OnActivateAsync()` and keep `OnInitialize` as it is. This makes things easier. Most time you want to load or refresh data in `OnActivateAsync()`. Most users just need one hook where it's possible to load data async and test it synchronous. 
Maybe just call both: `OnActivate` and `Task OnActivateAsync()` when caliburn activates a page. The developer can decide which one he overwrites and uses. This way we are backward compatible.
The most important thing would be the possibility to make `Task OnActivateAsync()` calls synchronous for integration and unit tests. 

I know this solution isn't super fancy, but better than nothing...

**Comment by nigel-sampson** [comment]
Ideally I'd have both as async, I've found assuming too much about use cases around data loading tends to find lots of other people who don't do the same thing as me 😄 

I'm not sure about having both `OnActivate` and `OnActivateAsync`. I like the idea of having both that way the developer can use the appropriate one.  However having two methods can make things more complicated for one people and I see a new class of issues when someone turns `OnActivate` into `async void` and then things will just get weird. Is the risk of this worth the pain of dealing with `OnActivateAsync` when you're only doing sync code?

Would love to hear everyone's thoughts?

**Comment by Athari** [comment]
Writing async methods when all you need is sync code, is a little annoying. Let's say I do:

    public Task OnFooAsync() { /*...*/ }

This will cause an error. I need to return something:

    public Task OnFooAsync() { /*...*/ return Task.CompletedTask; }

However, `CompletedTask` is only available since .NET 4.6. Otherwise I need to write something less pretty:

    public Task OnFooAsync() { /*...*/ return Task.FromResult(0); }

Of course, I can also use async-await:

    public async Task OnFooAsync() { /*...*/ }

However, if I don't have any `await` statements, I'll get a warning. So the code becomes:

    #pragma warning disable 1998
    public async Task OnFooAsync() { /*...*/ }

No matter what option I choose, my code becomes less pretty. And pretty code is the exact reason why use Caliburn.Micro and not something else.

So, while I badly need async-await functionality, I don't like the option of having only async-await version that much. I guess the code of the library will become much less pretty, which is unfortunate, but if it makes my code prettier, it's worth it, I'd say.

---

If you're asking whether there should be `Screen.OnActivate`+`AsyncScreen.OnActivateAsync` or `Screen.OnActivate`+`Screen.OnActivateAsync`, I don't have a strong opinion. .NET tends to combine both sync and async methods in one class, so I'd say the latter would feel more natural.

I see your point with "upgrading" `OnActivate` with `async void` though. You can add those Rolsyn code-checking things to warn devs about `async void` on screen callbacks. Not that it would be bullet-proof, but should be safe enough.

**Comment by nigel-sampson** [comment]
Yeah, I think the latter approach of having two methods may be better, some such as `CanClose` may however just be async.

**Comment by macsux** [comment]
I've actually built async version of screens for my project as I do quite a lot of async initialization. My initial attempt was to use a single class as well, but I quickly abandoned the concept. The issue came when you started mixing API. An invocation of activate method ensures that initialize has been called (and completed). If you have a sync activate at best it can trigger async initialize but has no guarantees that it completes before calling OnActivate callback, which will break many assumptions the code may make. While you may be able to get around it with well defined "usage pattern rules" where sync methods only call sync invocators, this is non intuitive if you have both present on your screen class and people will make mistakes. Invoking async code from sync methods created way too many problems. If you guys are interested, I can share the relevant classes on how I did it.

**Comment by Athari** [comment]
@macsux I think mixing sync and async methods in one class is an issue which can be checked using Roslyn code analyzers (and maybe R# addon). You can even offer an automatic code fix which makes all invocations sync or async within a class (this can be more complex if breaking code is to be avoided, I guess). It's easy to make a mistake only if IDE has no checks.

**Comment by nigel-sampson** [comment]
@macsux externally from `Screen` all activation will have to be asynchronous (which has some interesting flow on effects).

So I'd expect to see `IActivate.ActivateAsync`.

The implementation of would check for initialisation and if needed call the sync `OnInitiaize` and then await the `OnInitializeAsync` followed by doing the same thing for Activate.

This way dealing with two is encapsulated into Screen and not leaky.

**Comment by macsux** [comment]
That would work, though I didn't wanna touch the code outside the screens when I built my implementation that's why. Keep in mind that you have other places that may introduce breaking, such as ScreenExtensions where you got public methods like TryActivate. In my version I added TryActivateAsync in there, but if you leave existing TryActivate sync method you run into the same leaky mess as anyone invoking it would expect that viewmodel is activated after method is completed. 

The version that I did for my project, I modified and settled on the following classes that I had to create/modify (these are copies of original caliburn classes that I modified to use async everywhere - as I mentioned I didn't use single class solution):
ConductorAsync
ConductorBaseAsync
ConductorBaseWithActiveItemAsync
ConductorWithCollectionOneActiveAsync
IActivateAsync
IConductorAsync
IDeactivateAsync
ScreenAsync
ScreenExtensionsAsync

**Comment by altso** [comment]
What about deactivation? If I understand correctly, it might occur before initialization/activation is finished (e.g. user closes a page before all the data is loaded). I believe it could be addressed by supporting `CancellationToken` in `IActivate.ActivateAsync` method.

**Comment by danielmarbach** [comment]
I was reviewing the code base today what would be necessary to make it async. Currently the only true async support is available on the action methods by allowing the users to specify action methods which return a task and end with "Async" implemented by @BrunoJuchli in #154.

All other methods need either to be marked `async void` which has severe implications for the framework since it is a fire & forget operation (code is executed synchronously until the first `await` statement and then the invocation is done for Caliburn).

Results need to have an async void Execute method as well and the users need to do a lot of internal exception handling in order to properly fire the completed event. For example:

```
public class AsyncVoidSayHelloResult : IResult
    {
        private CancellationToken token;

        public AsyncVoidSayHelloResult(CancellationToken token)
        {
            this.token = token;
        }
        public async void Execute(CoroutineExecutionContext context)
        {
            try
            {
                await Task.Delay(5000, token);
                Completed(this, new ResultCompletionEventArgs());
            }
            catch (OperationCanceledException)
            {
                Completed(this, new ResultCompletionEventArgs { WasCancelled = true});
            }
            catch (Exception ex)
            {
                Completed(this, new ResultCompletionEventArgs { Error = ex });
            }
        }

        public event EventHandler<ResultCompletionEventArgs> Completed;
    }
```

if the user accidentally writes `ConfigureAwait(false)` into the await statements of the result implementation is going to blow up because the Completed event will be raised potentially on a non-sync context aware thread.

The die is cast guys. Async is coming more and more. Multiple OSS frameworks are moving to async only APIs. Those who still haven't bought into that idea are going down the cumbersome and error-prone path of implementing the sync and the async APIs redundantly and therefore wasting precious development resources. I think caliburn micro could take the lead and do the following

* Release a version 4.0 of Caliburn.Micro which is async only, the screen and conductor life cycles return tasks, IResult will be task-based and so on
* On older platform's where async/await is not supported drop those (let's face it those platforms are probably "obsolete anyway")
* Drop the silly async suffix convention, In the modern async world the async suffix is highly questionable. We at Particular Software stopped using it. See reasoning
https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix Other opinions https://blogs.rocksolidknowledge.com/2015/12/02/lets-stop-the-async-suffix-bullshit/, More frameworks like quartz.net will jump on that bandwagon.

Yes, I know this sounds like a drastic manner. But let's face it, we have to move on and adapt to the new world. Blocking operations are a thing of the past, and it is simple to build synchronous APIs into asynchronous APIs but extremely hard to build asynchronous APIs into synchronous ones. Some users might shout out and say but what about my platform XYZ. Well to be fair Caliburn.Micro is pretty much feature-complete and those users can stay on the 3.x versions without any pressure to update.

If you are willing to take the leap, I'm willing to help you out. Embrace the async future, it is happening now :dancing_men: 👯

**Comment by macsux** [comment]
I would agree with @danielmarbach that support for sync should be dropped and replaced by full async, which would be breaking change, warranting 4.0 designation. Considering Caliburn.Micro is a UI framework where responsiveness is key, having a sync syntax only encourages people to go down the wrong rabbit hole that they may have to dig out later when they realize that their screen is freezing while something is loading.

**Comment by nigel-sampson** [comment]
@altso You're right that all of this will need to support cancellation.

@danielmarbach it's certainly an interesting idea to go "full async", if it is decided then I'd probably want a bridging version `4.0.0` that still offered sync overrides for things such as `OnActivate` potentially marking them as deprecated for removal in `5.0.0`.

**Comment by danielmarbach** [comment]
This would mean full redundant in
implemention of the two paths. Are you really sure it is worth the effort? What does the deprecation offer in that regard? Maybe a good migration guide is enough. Happy to discuss this and bring my experience to the table

**Comment by nigel-sampson** [comment]
Not fully redundant code paths.

Right now the biggest pain points around async are the methods on `Screen` such as `OnInitialize` and `OnActivate` etc. With these not being async coordinating some things become awkward. Important to note here is these methods are protected and are not part of the public contract `IActivate`.

What I mean by having the non async support is that while the method on the public interface will definitely be async there would be two methods to override (one async and one sync) depending on the users need at the time.

The above conversation on the thread discusses some of the pros and cons.

**Comment by PatrickKunz** [comment]
@nigel-sampson I also think it's not required to stay backward compatible. Async is the way to go. It's nothing worse than a async / sync mix. Think about the back end. It has to be async and sync too in this case...
We have a project with hundreds of caliburn screens and conductors and we do not fear any migration because:
1. Version 3 is stable and we can stay on it as long we want. 
2. Migration is easy. All you have to do is to change the method signature and return something like Task.CompletedTask if you don't have any async code. 

Point 2 maybe sounds like some work for nothing, but you are prepared for the future if you do this.

**Comment by nigel-sampson** [comment]
I don't think this will be backwards compatible at all, async tends to have ripple affects on almost everything.

@Athari's comment above is probably the best description of the problem. If I don't have any async code for my activation the dealing with an async version of `OnActivate` adds more ceremony.

**Comment by danielmarbach** [comment]
Ok. Is it really that hard to return Task.CompletedTask for the once that override?

**Comment by nigel-sampson** [comment]
`Task.CompletedTask` doesn't exist everywhere sadly. Given this is only on the internal methods of Screen it's not a biggy and can be discussed in time.

**Comment by PatrickKunz** [comment]
It's even simpler. Task.CompletedTask isn't required in most cases. You just have to add the await keyword like this: `await base.OnActivate()` because you always have to call the parent anyway.

**Comment by nigel-sampson** [comment]
Unless you have your own base class calling the base isn't necessary in Caliburn.

Simply `return base.OnActivate();` would be enough, better in fact since we don't add the compiler overhead to a method for no reason.

Thoughts on that being low enough ceremony?

**Comment by danielmarbach** [comment]
That would be good enough. Another provoquing thought though: what is the purpose of a base method to override which does nothing? You could also make those optional interfaces to implement

@patrickkunz the async keyword without an await statement would lead to compiler warnings you'd have to supress. Ugly

**Comment by PatrickKunz** [comment]
@danielmarbach the first part of your post points to our issue. We just didn't know that we don't have to call OnActivate() to the caliburn base class. Otherwise we could do `await base.OnActivate()`. But i see that it needs a Task.TaskComplete somewhere if you run sync code.

**Comment by nigel-sampson** [comment]
Having the method that does nothing simply provides an extension point, the base class implements the interface and provides the hook. Doing it this way means that you don't have a whole class of errors where the developer didn't call the base method.

**Comment by danielmarbach** [comment]
Sorry don't follow. My only point was the base class method is not necessary when the user could implement the methods directly by implementing the interface. The only drawback: it is less discoverable because intellisense doesn't work

**Comment by nigel-sampson** [comment]
No worries, wasn't my best explanation

`Screen` and some of the other classes implement `IActivate` which has the method `Activate`, these classes often do some set up work here. 

For instance if this is the first activation then `Screen` will call `OnInitialize` and then `OnActivate`, subsequent calls will only call `OnActivate`. These methods don't do anything but allow the inheriting class to extend add behavior to the lifecycle. 

By splitting the methods the end developer overrides from the interface then we can ensure an accidental override that doesn't call `base.OnActivate` doesn't mess up this behavior.

**Comment by nigel-sampson** [comment]
Most of the interfaces on the `dev/4.0.0` branch are now converted across to be async and it's close to where I think we can do the next alpha.  

The bits left that can come in the next alpha are
- Window Manager
- Navigation Services
- Bootstrappers / Applications

Before we actually do the alpha I'd love for interested parties to check out the branch and have a play. One of the problems that contributed to this taking longer than hoped was getting confidence in consistent repeatable builds. Having others verify that they're having no build issues would be great.

Overall the journey to get there with the new project system was a bit of a journey but I'm happy to where we got to, however it does come with more breaking changes beyond just the async stuff.  These include

- Minimum version for Caliburn.Micro.Core upped to .NET standard 1.3
- Minimum version for Caliburn.Micro.Platform for WPF has been pushed to .NET Framework 4.6
- Minimum version for Caliburn.Micro.Platform for UWP has been pushed to 16299.
- We're now depending on Xamarin.Forms 3.0.0.561731.

Also assembly names are now related close to project name `Caliburn.Micro.Core` and `Caliburn.Micro.Platform`.

Having `Caliburn.Micro.Xamarin.Forms` as a separate package with it's own assembly and namespace I've come to the conclusion that this is failed experiment in over engineering to deal with having both Caliburn.Micro for Android while also supporting the Xamarin.Forms version at the same time.

By deprecating this assembly and collapsing back into Caliburn.Micro.Platform we can kill Platform.Core. Yay.

The samples have been updated to show some of this working.

Would love to get feedback.

**Comment by BrunoJuchli** [comment]
@nigel-sampson 
Great to hear.

The Xamarin.Forms dependency is only for non .Net Framework platforms, right? So WPF will still work w/o Xamarin Forms?

**Comment by nigel-sampson** [comment]
If you're adding a dependency to a `net46` project then it won't bring in Xamarin.Forms as expected.

The curly one here is `netstandard2.0` which I'm currently treating as a `Xamarin.Forms` project and bringing it. Would love to get feedback here as well.

**Comment by nigel-sampson** [comment]
Thinking about this over the weekend. My understanding is the WPF on .NET Core won't be .NET Standard. Because of this we can still go with the assumption that `netcoreapp` will be WPF (on .NET core) and `netstandard` is Xamarin.Forms.
