### ISSUE TITLE
Change request: Singularize

### ISSUE THREAD

**Issue by Werewolfkiss** [Caliburn-Micro/Caliburn.Micro#250]
Ran into an issue where the naming conventions didn't properly understood that
Batches and SelectedBatch where supposed to link. This is because the default Singularize only removes trailing s or ies. 

Fixed it by using PluralizationService.CreateService(CultureInfo.CreateSpecificCulture("en-US")).Singularize; from the System.Data.Entity.Design.PluralizationService

Don't know if it's possible to work this into caliburn itself..

**Comment by nigel-sampson** [comment]
It most likely wouldn't be possible to use that service since it's not available on all platforms that Caliburn.Micro is.

There a few other libraries out there that offer similar functionality such as the awesome [Humanizer](https://github.com/Humanizr/Humanizer), however taking a dependency on something like that for a small piece of functionality may not be the best idea either.
 
Potentially [Inflector](https://github.com/srkirkland/Inflector) may be a better direction.

We could add some better documentation around customizing this.

**Comment by cprieto** [comment]
@nigel-sampson I am just curious, is this going to be added to the documentation (about where to do it) or offering a better support for it?

**Comment by nigel-sampson** [comment]
Yeah, sorry it's certainly fallen off the backlog.

Here's some guidance on changing `ConventionManager.Singularize`, for this example we'll use the awesome library [Humanizer](https://github.com/Humanizr/Humanizer).

In your app setup code add the following

``` csharp
ConventionManager.Singularize = original => original.Singularize(inputIsKnownToBePlural: false);
```

**Comment by nigel-sampson** [comment]
Documentation updated.
