### ISSUE TITLE
[UWP] DisplayRootViewFor + EventAggregator issue in HelloUWP sample

### ISSUE THREAD

**Issue by coder89** [Caliburn-Micro/Caliburn.Micro#252]
Hi,

I'm working on an app using Caliburn.Micro (based on HelloUWP sample) and I hit an issue.

https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3.0.0/samples/Caliburn.Micro.HelloUWP/Caliburn.Micro.HelloUWP/App.xaml.cs

The sample calls DisplayRootViewFor() for every launch and the ShellViewModel is registered with PerRequest() method. Then ShellViewModel subscribes for EventAggregator events in Activated() method.

Now the problem.

Let's imagine we have a tile or a toast message that launches the app via launch activation protocol (similarly as if the app was launched from the app menu). If the app was already launched the framework will create a new instance of the ShellView and ShellViewModel. Deactivated() method for the old instance is never called (bug?) so we actually never unsubscribe from the EventAggregator (this is a singleton). The new ShellView will take ownership of the window but since the old ShellView is still in memory (it's a clear mem leak?) we will never receive any events as the old (that is no longer visible on screen) will get them all first. 

I think I might have solved this issue by simply registering the ShellViewModel using a Singleton<T>() method. It seems to work and it doesn't reinitialize the entire window and events are being sent and received on the other end as expected. 
Looked at the Caliburn.Micro source a bit and I think that the code flow will look similar as for the Blank App template in VS that is:
 - Check if there is a frame (if not create new and initialize everything from scratch)
 - if yes then check the type of the content and if it is the same as the main page do nothing.
 - Otherwise navigate to a new page that has been requested.

Do you see any potential issues with this "workaround" that I made?
If not should the Caliburn sample get an update?

Thanks,
Lukasz

**Comment by nigel-sampson** [comment]
Thanks for this. This sample is quite different from the other WinRT samples in that the root visual element is not a `Frame`, but is `ShellView` which itself contains a `Frame`. This enables the "master page"  style functionality where the sidebar is shared across all the views.

This is why we're using `DisplayRootViewFor<>` rather than `DisplayRootView<>`.

The solution you've proposed would work well with an app that had a `Frame` as the root element such as Windows 8.1 solution. I'm 100% sold on the `ShellViewModel` as a singleton, you'd reuse the same view model but end up wiping out the window content with a new view.

For this one it's much the same solution, but instead of step one you're checking whether `Window.Current.Content` is null or if it's already set to `ShellView`.

What I'd then do is rather than navigate publish something over the event aggregator about the tile or toast that the `ShellViewModel` can respond to, whether that's navigating the internal frame or not.

Does this make sense?

**Comment by coder89** [comment]
Thanks for your feedback. 

Now, after 6h of solid sleep I can see it better now. Actually, I have already implemented similar mechanism for all other app activation methods (i.e. Protocol or Voice) but not for the default one that corresponds to normal launch and tile/toast launch. :)
And of course I have implemented some kind of universal page navigation protocol with event aggregator that doesn't care what caused a launch but it only cares about launch/activation args. I will just reuse it for tiles/toasts and problem is solved for me.

I agree, having just a Singleton() as a solution won't work cause the ViewModel could even end up having 2 views in a dictionary and if it tries to access a view directly it wouldn't know which one. However, this is not the case for me.

And now slightly less related. Is there a good, built-in and reliable way of making sure that a current root view model got activated? I subscrbe/unsubscribe for events in Activate/Deactivate methods. Therefore, there are two cases when simply sending an event via Publish right after calling DisplayRootViewFor() silently fails. 
1. If app is not running then I can listen to Window.Current.Activated event and this is the earliest time when I can send and successfully receive any event in ShellViewModel. Doing it before does not deliver any events to ShellViewModel as its' Activated() method hasn't been called yet.
2. Contrary to that if an app has already been running and window was active and something (i.e. a toast) causes app launch then I can send an event immediately. Also Window.Current.Activated won't be raised so solution from 1. wont't work. 

I know I could just access ShellViewModel or even ShellView directly and pass some parameters or call some method to achieve the same. But I want to keep only a single protocol for frame navigation and doing it directly feels kinda hackish/ugly to me. :)

Thanks,
Lukasz

**Comment by nigel-sampson** [comment]
Just thought of a different solution where instead of checking `Window.Current.Content` you can just check to see if the container as an instance of `INavigationService`, if so then the shell is already set up and you can call the navigation service directly.

At the moment there isn't much that deals with the life cycle of a root view model like that. Normally it's the responsibility of the conductor that owns that view model. When you're doing a view first style approach the navigation service takes the role of the conductor.

Right now you could check if the shell view model is initialized (and if not set it up via `DisplayRootViewFor<>`) before dispatching any events.

This would ensure that the shell is always active before events are sent.

**Comment by coder89** [comment]
I'll stick to checking the `WIndow.Current.Content` as in my app there is one very special case where ShellView needs to be swapped temporarily with a normal page (not enabled with Caliburn.Micro) to improve launch time.

When it comes to events the problem is that Loaded event (where I init the `INavigationService`) is raised after launching/activation is done. Therefore, receiving an event (that required the service) fails to do anything. I'll simply store the event and process it when the service is initialized and registered (same as with resuming message in sample app).

I think I have a clear picture of the whole navigation/launching limitations and I'll workaround them tomorrow. Closing the issue for now.
