### ISSUE TITLE
How to automatic raise property change?

### ISSUE THREAD

**Issue by lyqscmy** [Caliburn-Micro/Caliburn.Micro#255]
When guard methods(or property) have complex dependency,it's really annoying to declare every dependency property change.It feels like human work for framework, not conversely.

For example

``` C#
public State state
{
   get { return _state; }
   set
   {
       _state = value;
       NotifyOfPropertyChange(() => state);
       NotifyOfPropertyChange(() => CanYuxianjb);
       NotifyOfPropertyChange(() => CanHandShake);
       NotifyOfPropertyChange(() => CanFire);
       NotifyOfPropertyChange(() => CanStop);
       NotifyOfPropertyChange(() => CanJcjb);
   }

}
```

It will be nice if I don't need state property,just change _state will automatic raise all Can* property change.

In the follow code, I have to add a alias state for App.MainBoard.IsConnect  and hand write NotifyOfPropertyChange Explicit.I think there should be a convention to make life esaier.

``` C#
public bool Connect()
      {
          return App.MainBoard.Connect();
      }

public bool CanConnect()
{
    return !App.MainBoard.IsConnect;

}

public bool Disconnect()
{
    return App.MainBoard.Disconnect();

}

public bool CanDisconnect()
{
    return App.MainBoard.IsConnect;

}
```

**Comment by nigel-sampson** [comment]
For the first problem I'd look into something like [Fody.PropertyChanged](https://github.com/Fody/PropertyChanged) as that sort of code analysis and generation isn't something that should be in an MVVM framework.

With it you can do something akin to

``` csharp
public Static State { get; set; }

[DependsOn(nameof(State))]
public bool CanFire { get { return ...; } }
```

In my opinion around *Is** wouldn't make sense given the way it's used in English sentences. I'd also note that your example wouldn't work with this convention due to `CanConnect` being the negation of `IsConnect`.

I'd be happy to open up the convention so people can add their own guard prefixes though and have raised an issue for that.
