### ISSUE TITLE
Child OnDeactivate never called when Parent Deactivate(true)

### ISSUE THREAD

**Issue by Hikerakashiya** [Caliburn-Micro/Caliburn.Micro#272]
I have a parent view model that is a conductor with a tab control and children view models that are screens. I create an instance of the parent view model and add the children view models by calling Items.Add on the parent view model. Before adding the children view models I set the child view model Parent = this and ConductWith(this). After this I call WindowManager.ShowWindow(ParentViewModel) and display the parent view model. When the parent view model is activated, the children view models are activated. 

Now when the parent video model is deactivated via clicking the close button on the window, which passes true for the close variable, none of the children view models are deactivated. However if I deactivate the parent view model with a close of false, all of the children view models also have their deactivate methods called. Is this supposed to happen like this? I want to be able to call specific logic on my children view models that is only triggered when close is equal to true for OnDeactivate. Currently the only way the children OnDeactivate methods are called is if close is false which prevents me from having a conditional if(close) { //Do Something }. 

```C#
public class Parent : Conductor<IScreen>.Collection.OneActive
{
/// When OnDeactivate(false), all the children OnDeactivate methods are called, OnDeactivate(true), none of the children OnDeactivate methods are called.
        protected override void OnDeactivate(bool close)
        {
            base.OnDeactivate(close);
        }

        public void AddTab(IScreen screen)
        {
            screen.Parent = this;
            screen.ConductWith(this);
            Items.Add(screen);
        }
}

public class Child : Screen
{
/// This is only called when the Parent has OnDeactivate(false). When the Parent has OnDeactivate(true) this is never called.
        protected override void OnDeactivate(bool close)
        {
            if (close)
            {
                // Do Something Before Closing
            }
            base.OnDeactivate(close);
        }
}
```

**Comment by nigel-sampson** [comment]
There's a few different things going on here to complicate the problem.

The first is that using `ConductWith` probably isn't the best approach, this is normally used for more sort of adhoc compositions rather than with the conductor. All this method does is chain through the activates and deactivates from parent to child, but doesn't do anything if the parent is already active.

Replacing `AddTab` with the following will do all of the previous code but also ensure the current active item is deactivated and activate the new item.

``` csharp
public void AddTab(IScreen screen)
{
    ActivateItem(screen);
}
```

As to the close behavior, the conductor when not closing only tries to deactivate the active item. When closing it closes all items. Because of the above problem you didn't have an active item so nothing was being deactivated.

**Comment by Hikerakashiya** [comment]
Thanks for the help! I cleaned up my code with using just the ActivateItem(screen). I also figured out I was erroneously returning before base.OnDeactivate(close); was being called which prevented me from seeing the OnDeactivtate fire down the hierarchy.
