### ISSUE TITLE
INavigationService doesn't work after resuming the application

### ISSUE THREAD

**Issue by R74NN** [Caliburn-Micro/Caliburn.Micro#277]
Hi,

this is reproducible on the HelloUWP sample.

On WP10 (device/emulator) when I hit the back or start button, the application get's "suspended" but CaliburnApplication.OnSuspending() is not actually called (which I suppose doesn't have to be necessarily an issue). 

But when I start the app again from the app list (PreviousExecutionState == ApplicationExecutionState.Running), the navigation service doesn't work anymore. Calling it's Navigate methods does nothing and the Frame stays blank.

Summary:
1. Start the app
2. Exit the app (back/start button pressed)
3. Start the app again
-> frame navigation doesn't work

Thanks.

**Comment by nigel-sampson** [comment]
It looks like what's happening is the view is being recreated when the app is relaunched for the second time. A bit surprising since this wasn't the behavior in Windows Phone 8.1.  With some more investigation it appears that there's a difference between going back into the app via holding back and picking the app versus launching the app which is surprise.

What this means is that we'll need to re-register the navigation service.

Adding the following to the top of `SetupNavigationService` will resolve this. I'm in the process of updating the samples so will make sure this is added.

``` csharp
if (_container.HasHandler(typeof(INavigationService), null))
    _container.UnregisterHandler(typeof(INavigationService), null);
```

Regarding the suspension, using the debug tool to send a suspension worked correctly, but navigating out of the app didn't call `OnSuspending`. This seems to be a platform issue as we're not going anything special here, just attached to the Suspending event.

**Comment by R74NN** [comment]
Thanks for the fast reply and looking into the issue. After adding your code, re-running the app works as expected.
