### ISSUE TITLE
Unexpected outcome for Message.Attach on a RadioButton 

### ISSUE THREAD

**Issue by taori** [Caliburn-Micro/Caliburn.Micro#288]
For a RadioButton the attached handler should only be called if the element in question is not already checked. I think that's what most people would expect it to behave like at least.

**Comment by nigel-sampson** [comment]
Sorry can you expand on what you mean here?

**Comment by taori** [comment]
Yes, of course.

Basically in my xaml i have a declaration like <RadioButton cal:Message.Attach="SomeMethod('somevalue')"> This method is called whenever i click on the radiobutton. Even if it was already checked before clicking the RadioButton. I think for a common scenario where RadioButtons are used this would be unexpected. It's not a serious issue obviously

**Comment by nigel-sampson** [comment]
Ah ok, currently the convention for a `RadioButton` is wrapped up in the convention for `ToggleButton` which it derives from. This convention looks like
```
AddElementConvention<ToggleButton>(ToggleButton.IsCheckedProperty, "IsChecked", "Click");
```
There the last parameter is the default event that triggers attached messages. Looking at the definition of `ToggleButton` there is an event `Checked` that would only fire when the radio button is checked, but not unchecked which could be what you want. In this case you can override the default convention by having the following in your setup code.
```
AddElementConvention<ToggleButton>(ToggleButton.IsCheckedProperty, "IsChecked", "Checked");
```
I'm hesitant to change default conventions like this because it could be a massive breaking change to any code that depends on the current convention.

**Comment by BrainCrumbz** [comment]
@taori could you edit your second comment, after *[...] declaration like*. I guess there must be some XAML that has not been rendered by github because of < / > signs

**Comment by taori** [comment]
@BrainCrumbz oh dear. took me a while to react but i did it now.

**Comment by BrainCrumbz** [comment]
Thanks. In the meantime, totally forgot what was the originating issue! It'll be useful for future readers anyway.
