### ISSUE TITLE
PropertyChangedBase.NotifyOfPropertyChange optimization

### ISSUE THREAD

**Issue by xmedeko** [Caliburn-Micro/Caliburn.Micro#295]
I would like to optimize `PropertyChangedBase.NotifyOfPropertyChange` to check for `PropertyChanged`:
``` c#
    public virtual void NotifyOfPropertyChange([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null) {
        if (IsNotifying && PropertyChanged != null) {
            Execute.OnUIThread(() => OnPropertyChanged(new PropertyChangedEventArgs(propertyName)));
        }
    }
```

It will prevent unnecessary `new PropertyChangedEventArgs` creations.

**Comment by nigel-sampson** [comment]
That makes sense, you'll also need to change the line below as currently it's never null (which is why there's no check currently).

``` csharp
public virtual event PropertyChangedEventHandler PropertyChanged = delegate { };
```

However I can see that for a very commonly called event such as `PropertyChanged` this pattern can cause some performance degradation.

Happy to take a PR for this. :smile:
