### ISSUE TITLE
Action guard on event disables complete ListWiew/GridView control

### ISSUE THREAD

**Issue by wstaelens** [Caliburn-Micro/Caliburn.Micro#302]
Hi,

I have a View with this:
```xml
    <ListView x:Name="lvTest" ItemsSource="{Binding TestItems}"
      cal:Message.Attach="[Event MouseDoubleClick] = [Action Edit()]"
      SelectedItem="{Binding DataContext.SelectedTestItem, ElementName="lvTest">
      <ListView.View>
        <GridView>
           <GridViewColumn Width="30" 
                          DisplayMemberBinding="{Binding ID}" 
                          Header="Id"
                          utils:GridViewSort.PropertyName="ID" />
        </GridView>
      </ListView.View>
    </ListView>

    <StackPanel Grid.Row="2" Orientation="Horizontal" HorizontalAlignment="Right">
      <Button x:Name="Edit" Content="Edit" Margin="3" MinWidth="75"
              cal:Message.Attach="[Event Click] = [Action Edit()]" />
    </StackPanel>
```

The ViewModel has this code:

```csharp
    public bool CanEdit    {
      get { return SelectedItem != null; }
    }

    public void Edit()
    {
       // ...
    }
```

Now when I run my application the GridView is disabled.
When I change the Event to another method (e.g. Edit2()) on the GridView, the GridView is not disabled anymore, which is ok:
```xml
cal:Message.Attach="[Event MouseDoubleClick] = [Action Edit2()]"
```

Is this normal that the guard disables the complete ListView/GridView control when it is only attached to the MouseDoubleClick, or is this a bug in Caliburn.Micro?
With how it works currently I can't even attach multiple caliburn events to my gridview.

**Comment by nigel-sampson** [comment]
This is expected behavior, you're applying an action to two different controls in the `Button` and the `ListView`, there's no way for the framework to determine that you only want to apply the guard property `CanEdit` to one and not the other.

You can either create a second `Edit` method as you mentioned, or rename the guard property and bind it yourself to the button.

**Comment by wstaelens** [comment]
Ok I understand, but for the ListView/GridView the Edit() action is attached to the MouseDoubleClick event, so the CanEdit guard should also apply only to the MouseDoubleClick event, thus ignoring/disabling the MouseDoubleClick event.
Now the complete control is disabled.
So attaching multiple actions to a ListView/GridView each with different guards results that one guard can disable the complete control while you just want to disable an event?

feels "strange" to me, but I'll accept your answer if this is nothing that can be done. Just opening the discussion as I felt that it behaved strange.

**Comment by nigel-sampson** [comment]
Caliburn has always applied the guard to both the event and to disable the control if the guard returns false. 

I agree for your scenario it can look strange but we do this irregardless of the event because it's incredibly subjective which events / control combinations would warrant not disabling the control.

**Comment by wstaelens** [comment]
ok thanks for the info.
