### ISSUE TITLE
Extract EventAggregator?

### ISSUE THREAD

**Issue by Bl0tt0** [Caliburn-Micro/Caliburn.Micro#313]
I just found myself using the Caliburn EventAggregator in a Windows service. Being a service you can see that it doesn't need any of the UI stuff. So i copied the EventAggregator related code to avoid the UI dependencies in my service. I would have loved to just install a Caliburn.Micro.EventAggregator package. The Core could be dependent on that package so that nothing changing for users who need the complete framework.
Is such a separation something you considered previously?

**Comment by nigel-sampson** [comment]
We did have this sort of in the first few version < `2.0.0`. `EventAggregator` was published as a "source package" which had the source for it inside. With `2.0.0` and the shift to the portable class library and having to inject the `PlatformProvider` it made no sense for this to continue.

If we did try to break it out to a separate package we'd probably need to break out it's dependencies since other similar packages such as `SimpleContainer` may depend on them, and even then it would still need some mechanism for injecting the platform specifics.

Ultimately it's a path I don't think we'll go down with the extra complexity sorry.
