### ISSUE TITLE
Cannot use MasterDetailPage in xamarin form

### ISSUE THREAD

**Issue by kida7** [Caliburn-Micro/Caliburn.Micro#338]
I have tried to set up caliburn with xamarin form but it does not work with MasterDetailPage? Is it a bug, or MasterDetailPage is not supported?

**Comment by nigel-sampson** [comment]
Yup, you can use `MasterDetailPage`, the difference in say the [Hello.Forms](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/Hello.Forms) sample would look something like this.

``` csharp
namespace Hello.Forms
{
    public class App : FormsApplication
    {
        private readonly SimpleContainer container;

        public App(SimpleContainer container)
        {
            this.container = container;

            container
                .PerRequest<MasterViewModel>();

            Initialize();

            DisplayRootViewFor<MasterViewModel>();
        }
    }
}
```

The key differences, we're not overriding `PrepareViewFirst` since we're no longer using `NavigationPage` and we're calling `DisplayRootViewFor<MasterViewModel>();` instead of `DisplayRootView<LoginView>();`. Notice it's a different method and passing the view model that pairs with the `MasterDetailPage`.

**Comment by GuyMicciche** [comment]
Could you please provide how I we can navigate using MasterDetailPage? This would be so helpful. Even a simple example would be fantastic!
