### ISSUE TITLE
IHandle marker interface needed?

### ISSUE THREAD

**Issue by jonnybi** [Caliburn-Micro/Caliburn.Micro#347]
First of all thanks for your great work!

I wonder if you guys can get rid of the IHandle marker interface if you query the 
generic IHandle<T> interfaces in this fashion:

`var interfaces = handler.GetType().GetInterfaces().Where(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IHandle<>));`

Or do i omit something?

**Comment by lploumen** [comment]
I guess it should work since IHandle is not used and the generic interface can be queried like you propose.

**Comment by nigel-sampson** [comment]
It probably could be removed. Can't see anyone using it at the moment, but could be a breaking change to remove it.

Will look into it.

**Comment by jaredthirsk** [comment]
Any thoughts about going in the opposite direction, and having only an IHandler marker interface, and using reflection to find methods matching the pattern void Handle(T message)?

The author of StructureMap is doing this and going a step further, requiring no marker interface (but requiring a convention of a class name ending in Handler).
https://jeremydmiller.com/2017/05/25/message-handlers-in-the-new-jasper-service-bus/

I'm also rolling my own that I may open-source at some point soonish (somewhere in https://github.com/jaredthirsk/core), and my preferred approach may be to scan for methods on classes with the IHandler marker interface, or forego marker interfaces and scan all classes (maybe with a post-compilation static analysis to a reflection cache file to speed up start-up.)

I like the idea of avoiding a bunch of IHandler<> interfaces if I'm going to handle several message types.  I also like the idea of being able to avoid reflection if my goal is explicitness and/or fast startup times.

**Comment by nigel-sampson** [comment]
It's certainly something I've considered, While personally I like the idea, I'm not 100% sold on it being in the framework itself.

What I may do is put together a blog post / sample on how to create an "auto subscribing / handling" view model. I've built one before where the view model could have any method that match `HandkeX(T message)` would be auto wired up with a check for `CanHandlleX(T message)` as well.

This example hooked into the `ViewModelBinder` so only applied to the view models directly not to supporting service. Something similar could definitely be extended into startup configuration.

Thoughts?

**Comment by beachwalker** [comment]
Would be nice if you could set (e.g. when register the object) which of it's methods should be called. So you could wire everything up (using lambda like in rx instead of implementing special interface).

**Comment by jonnybi** [comment]
I personally like the _convention over configuration_ approach most new frameworks follow. 

But for me there are drawbacks.
All developers are forced to dive deeper into the frameworks too fully understand what's going on (that's maybe not a drawback but not all developers on a team are always willing to do this).

If you use multiple of these frameworks you most likely have one or many aspects in your viewmodels that are "hidden".

For example Fody PropertyChanged moved away from the ImplementPropertyChangedAttribute and as a convention every class that implements INotifyPropertyChanged is automatically weaved.
But I like these attributes because they make code more readable.

If caliburn moves away from the handle interfaces and other frameworks follow this approach you have to have a high awareness which frameworks are used in your project. Because an accidently chosen method name could have a huge impact.

I think a good example is the Startup class in asp.net core projects. There is convention used too but but the startup is used only for a single purpose and there are only the conventions of a single frame-work you have to know. But in viewmodels you most likely will hit multiple aspects...and then it's get messy...

**Comment by nigel-sampson** [comment]
I don't think I want to head down the convention over configuration approach too much for a lot of reasons above. It can cause too much confusion about what's actually happening under the covers.

We see this already a little with the binding / action conventions the framework already has and I'm not sure doubling down on it is the right idea.

The Fody example is a great one because my understanding is a little different than above in that Fody automatically added weaving to classes already implementing `INotifyPropertyChanged ` and you needed to opt out using a different attribute. `ImplementPropertyChangedAttribute` was only ever required on classes that wanted weaving but didn't already implement the interface.

At the moment I'd like to concentrate on things like
- Removing `IHandlle` if it's not being used, as I write this I can think of one reason why it may need to stay.
- Providing subscriber options for thread dispatching.
- Considering adding some async love.

At the same time making sure we don't stand in the way of letting people layer conventions down on top of this in a way that makes sense for them.
