### ISSUE TITLE
How to call ViewModel method from a MenuItem in Xamarin.Forms

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#355]
I have the following Xamarin.Forms code of a ViewCell template:
```xaml
<ViewCell.ContextActions>
   <MenuItem  IsDestructive="true"
                       Text="Delete" />
</ViewCell.ContextActions>

```
I intended to call a method from my viewmodel, so I added this:
```xaml
<ViewCell.ContextActions>
   <MenuItem cm:Message.Attach="DeleteItem"
                       IsDestructive="true"
                       Text="Delete" />
</ViewCell.ContextActions>
```
However, it throws a NPE:

> Object reference not set to an instance of an object.

I also have a Button in the view and it works:
```xaml
  <Button cm:Message.Attach="AddItem" Text="Save" />
```

I tried this way:
```xaml
cm:Message.Attach="[Event Clicked] = [Action AddItem()]"
```

With this there is no exception, but there is no method call at all.

Can I somehow call the method?

**Comment by nigel-sampson** [comment]
Trouble with `MenuItem` is the same with `ToolbarItem` which came up in #336.

Under the covers Caliburn.Micro uses the attached behaviors with things like `EventTrigger`. 

While EventTrigger<T> has a generic restriction to just BindableObject, the Triggers property is on VisualElement.

Since `MenuItem` doesn't inherit from VisualElement we can't attach our triggers to it.

From #336, work arounds are to use direct event handlers to bind to commands for those ones.

Regarding the full syntax, can you provide a sample where this isn't working. I just checked this on the new samples branch with [a new commit](https://github.com/Caliburn-Micro/Caliburn.Micro/commit/8c6c55e9f8fc3f753ae35914cb2773224c251585) that worked correctly.

**Comment by nologinatgit** [comment]
Thanks for the insight.
Regarding the full syntax, my post is misleading as I meant the MenuItem not the Button - Buttons are just fine :)
You mentioned two possible workarounds: events and commands. 
Strangely, _none of them seems to work._

I have the following code:

```xaml
  <ViewCell.ContextActions>
        <MenuItem x:Name="menuDelete"
                            Clicked="menuDelete_Clicked"
                            IsDestructive="true"
                            Text="Delete" />
  </ViewCell.ContextActions>
```
In my code-behind:
   ```csharp
 private void menuDelete_Clicked(object sender, EventArgs e)
    {
      (BindingContext as ViewModels.ListingsViewModel).Delete();
    }
```
I have a breakpoint here, but it is never hit.

Also, this code won't work either:

```xaml
<ViewCell.ContextActions>
        <MenuItem x:Name="menuDelete"
                           Command="{Binding Source={x:Reference listView},
                                          Path=BindingContext.DeleteCommand}"
                            IsDestructive="true"
                            Text="Delete" />
  </ViewCell.ContextActions>
```


Looks like some serious bug in Xamarin.Forms.
