### ISSUE TITLE
How to cancel navigation in Xamarin.Forms ViewModel

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#357]
I have a ViewModel (derived from Screen) and I use navigation to get to it.

When the user clicks the navigation back or presses the back button, I should prevent the navigation until a question is answered.

I know I can override `OnDeactivate` but it is triggered after the page has navigated back and the question looks odd on the other page.

I can see that there is a `CanClose `method but it is not triggered when I navigate back.

What can I do about this?

**Comment by nigel-sampson** [comment]
You should be able to use `CanClose`, if that's not working then it's most likely a bug in the Xamarin.Forms navigation service.

**Comment by nologinatgit** [comment]
Is it possible that I use it the wrong way? Can you confirm it on a sample project as well?
The `OnActivated `and `OnDeactivated `methods are called so I'd guess that CM is set up properly.
Can you give an estimation when you will release (or prerelease) v3.0.2?

**Comment by nologinatgit** [comment]
The problem is that I don't know any workaround or any way to cancel the navigation (regardless of CM).
I also need to cancel a tab page change but I can only rely on OnDeactivated (even the AttemptDeactivate event is after the navigation/tab change) and it is not what I intend to have.

Can you provide any hint how I should stay on a given Page?

**Comment by nigel-sampson** [comment]
I've just been looking into this some more,  so Caliburn.Micro has support for `CanClose` and it's only "sort of" implemented in Xamarin.Forms.

When navigating forward using the navigation service we check `CanClose` on the view model we're leaving.

However when the user initiates a back navigation via the header or the hardware back button we aren't. The reason is that currently the `NavigationPage` in Xamarin.Forms doesn't expose events relating to navigation. So we can't listen for those events and cancel them (if possible). It's certainly something I'd love to see added to Xamarin.Forms.

Looking around there doesn't seem to be a way to do this currently in Xamarin.Forms without falling back to the underlying platform, but you may have better luck finding a more specialized solution. If you do I'd love to hear it.
