### ISSUE TITLE
Passing parameters always null using a usercontrol with custom events

### ISSUE THREAD

**Issue by panhans** [Caliburn-Micro/Caliburn.Micro#363]
I have a usercontrol with a custom routed event:

```
public partial class DummyControl : UserControl
{
    public static readonly RoutedEvent ActionClickEvent = EventManager.RegisterRoutedEvent(
        "ActionClick",
        RoutingStrategy.Bubble,
        typeof(RoutedEventHandler),
        typeof(DummyControl));

    public event RoutedEventHandler ActionClick
    {
        add { this.AddHandler(ActionClickEvent, value); }
        remove { this.RemoveHandler(ActionClickEvent, value); }
    }

    public DummyControl()
    {
        this.InitializeComponent();
    }

    private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
    {
        this.RaiseEvent(new RoutedEventArgs(ActionClickEvent,this));
    }
}
```

In my xaml I'm using a datagrid and I want to pass the SlectedItem to my ViewModel. But when the event gets triggered, the passed item is alway null. When trying the same with an button everything works fine.

`<Cstm:DummyControl cal:Message.Attach="[Event ActionClick] = [Action Test(dataGrid.SelectedItem)]"/>`

Don't know if this is a known bug or if I missed something. :\

**Comment by nigel-sampson** [comment]
Given the method on the view model is being called there probably isn't an issue with the `RoutedEvent`. 

However to double check if you replace the custom control with a Button with the same `Message.Attach` (changing the event name) does the parameter get passed?

If that's fine then it could be something to do with the xaml rellated to the `DataGrid`. Can you expand on the xaml you've shown to include it?

**Comment by panhans** [comment]
Yes, if I take a button everything works fine and the parameter gets passed.

`<Button Content="Button dg" cal:Message.Attach="[Event Click] = [Action Test(dataGrid.SelectedItem)]"/>`

This is the method in my viewmodel 

```
public void Test(string test)
{           
}
```

And the DataGrid looks like this:

`<DataGrid ItemsSource="{Binding TestCollection}" IsReadOnly="True" Name="dataGrid"/>`

It's simply bound to a collection of strings.

Greets!

**Comment by nigel-sampson** [comment]
Thanks, so it looks like [this line](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/BindingScope.cs#L286) is the problem.

`FindScopeNamingRoute` normally navigates up the visual tree to find the naming root which normally the user control is (hence the break). 

For your circumstance the starting element is the user control so we don't look further up the visual tree. 

This definitely looks like a bug since if we're starting with the user control from the "outside" (for lack of better term) then we shouldn't stop.

The trick will be identifying when this is the case since attaching a message to the root element in the user control xaml will look exactly the same. I have a feeling this may end up as known issue.

For a work around you can use the long form syntax.

``` xml
<views:CustomView>
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="ActionClick">
            <cm:ActionMessage MethodName="ShowName">
                <cm:Parameter Value="{Binding ElementName=Names, Path=SelectedItem}"/>
            </cm:ActionMessage>
        </i:EventTrigger>
    </i:Interaction.Triggers>
</views:CustomView>
```

**Comment by nigel-sampson** [comment]
I don't believe there's a good solution to solving whether you're in or out of the user control when determining the naming root to stop at.
