### ISSUE TITLE
Declarative mapping ViewModel -> View

### ISSUE THREAD

**Issue by JobaDiniz** [Caliburn-Micro/Caliburn.Micro#373]
Is there a way to declarative map the ViewModel -> View in Caliburn?
Conventions are great, but sometimes declarative is required, like when code is _obfuscated_.

**Comment by nigel-sampson** [comment]
It depends a little on what your requirements are.  You can always override the conventions themselves by methods on `ViewLocator` and `ViewLocator`. For instance the below handles the views and view models being in different namespaces than expected.

``` csharp
ViewModelLocator.AddNamespaceMapping("Hubb.App.UWP.Views", "Hubb.Core.ViewModels");
ViewLocator.AddNamespaceMapping("Hubb.Core.ViewModels", "Hubb.App.UWP.Views");
```

If none of the methods provide what you need you can always change the behavior of the locators directly.

``` csharp
ViewLocator.LocateTypeForModelType = (modelType, location, context) => ...
```

For your specific example with obfuscation it becomes trickier since by definition you won't know the type names at development time and depending on the obfuscator even some of the namespaces may be changed.

You may end up with having to apply an attribute to the view / view model telling it the location of the other half of the pair. In this case you'll definitely need to customize the locators  directly.
