### ISSUE TITLE
Transition to async API

### ISSUE THREAD

**Issue by devhb** [Caliburn-Micro/Caliburn.Micro#391]
This is not an issue or feature request, it's more a discussion and I want to share my observations about moving the API of caliburn to only support an async version as also discussed [Full Async Support](https://github.com/Caliburn-Micro/Caliburn.Micro/projects/2).

I created a fork from the latest version where four commits have been done

1. From **void** to **Task** for and their implementations (https://github.com/devhb/Caliburn.Micro/commit/dc7a971b63e843b28dcf24d22ebeb88209014c2a)
- IActivate
- IClose
- ICloseStrategy
- IConductor
- IDeactivate
- IGuardClose

2. Added CancellationToken to async methods (https://github.com/devhb/Caliburn.Micro/commit/fbca8b67f034d7b0a17846ab207d3b2d738472c7)
3. Added cancellation (https://github.com/devhb/Caliburn.Micro/commit/9c6906346f2f5e07fa87090f2597b0c586289bc9)
4. Moved notification about the ActiveItem before calling Activate on the screen so the view is displayed before executing any code (https://github.com/devhb/Caliburn.Micro/commit/2decc680890dadfbd739b5b1a2278758f1810af6)

If point 4 is not done, we will see the view for the screen first when the "OnActivate" is completly run.

The current version from the fork is currently used in a WPF application to test it under production circumstances, till everything seems to working fine.

Open points
- how to best handle activate/deactivate (Should a screen handle it's own tokens if none where provided as method parameters?)

Any comments about the transition are welcome.

**Comment by veleek** [comment]
Can you clarify what you mean by "Should a screen handle it's own tokens?"  Are you talking about CancellationTokens? 

I'm excited to try out these changes.

**Comment by devhb** [comment]
Yes I am talking about CancellationTokens.

In the application where it is tested currently this is handled by an component which is responsible for cancellation of activate/deactivate.

```CSharp
public void SwitchContent(IShell shell)
{
    if (shell.SelectedSource == null) return;

    var targetUri = shell.SelectedSource;

    if (m_shell.ActiveItem != null && targetUri == ((IWorkspace)shell.ActiveItem).ToLink()) return;

    if (m_tokenSource != null)
    {
        m_tokenSource.Cancel();
        m_tokenSource = null;
    }

    var localTokenSource = new CancellationTokenSource();
    m_tokenSource = localTokenSource;
    // SwitchContentCore calls  
    // await m_shell.ActivateItem(workspace, cancellationToken);
    var activateTask = SwitchContentCore(targetUri, m_tokenSource.Token);

    activateTask.ContinueWith(t =>
    {
        try
        {
            if (!t.IsCanceled || !localTokenSource.IsCancellationRequested)
                return;             
        }
        finally
        {
            // clear global tokenSource to avoid a Cancel on a disposed object
            if (m_tokenSource == localTokenSource)
            {
                m_tokenSource = null;
            }

            localTokenSource?.Dispose();
        }
    }, localTokenSource.Token);
```

I think this is something that should be handled by a Conductor/Screen internally if no CancellationToken is passed to cancel the activation/deactivation process internally in a Conductor/Screen

**Comment by nigel-sampson** [comment]
Thanks for the work you've done, I'm snowed under but will certainly look over this soon.

From a quick glance it looks like you'e stripped out a lot of the other platforms. Did these work or removed for a first cut of this?

Cancellation tokens are going to be interesting, I think the general gist of what you're staying is correct. If a conductor is passed a cancellation token on activation and at the same time activates it's own children then the same token should be used. If later on the `ActiveItem` is changed then a new token would be created.

**Comment by devhb** [comment]
> From a quick glance it looks like you'e stripped out a lot of the other platforms. Did these work or removed for a first cut of this?> 

Sorry, I've forget this in the introduction post.
Yes, because I had problems building them and they are not interesting for us internally.

**Comment by nigel-sampson** [comment]
I'm most likely in agreement there. In the coming weeks I'll put together a way we can all approach / discuss this.

**Comment by veleek** [comment]
I don't have much of an issue with the way you're handling CancellationTokens.  I did want to comment on the method names though.  Standard practice is for Async methods to be called FooAsync (OnActivateAsync, etc.).  You've got this all in an assembly with a different name anyway, and it's not signature compatible with the existing stuff.  We should probably just go the entire way and rename everything.

**Comment by danielmarbach** [comment]
When the library is fully async, what I recommended, and not mixed mode then read our rational as well as the links provided in that doco

https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

**Comment by veleek** [comment]
Unfortunately there's a lot of existing code built around this library out there and without differentiating between the two I'm concerned that it could be easy to run into problems.  Just think about a scenario where you download the source for a library using Caliburn and build it into your project.  You now have an Screen that's using the new version of OnActivate but none of the code is awaiting the methods.  

Personally, I could argue it either way and if we want to go full hog one way or the other I would be okay with no Async suffix.  But then we should also not have a different assembly name, since there's no intention to have both versions in use side by side.  

Most of the projects that I've worked on that have transitioned to Async have had to support a bit of both worlds and the suffix tends to make that a little easier.

**Comment by devhb** [comment]
Yes @veleek, you are right that it breaks existing applications.
After migrating another application I got problems because I referenced v3 and the async version.

I than created a version with the Async in assembly and namespace name (different branch in the fork).

Another thing I missed when creating the async API was the `ConductorBaseWithActiveItem.ActiveItem` property:
```CSharp
/// <summary>   
/// The currently active item.  
/// </summary>  
public T ActiveItem {  
    get { return activeItem; }  
    set { ActivateItem(value); }  
}  
```
The is a call to
```CSharp
public abstract Task ActivateItem(T item, CancellationToken cancellationToken = default(CancellationToken));
```
I think the call should be removed and the activation has to be done at a different place.

**Comment by veleek** [comment]
Yeah, just making ActiveItem read-only and requiring the user to call ActivateItem seems like it would be reasonable to me.

**Comment by danielmarbach** [comment]
Completely agree that when doing mixed mode the async methods should follow the suffix convention. 

That being said from an async best-practices perspective synchronization is a concern of the user. A framework should pick an opinionated way and stick to it. Users mostly argue from a DRY perspective for having sync overload but that is totally pointless with async. Having two ways (sync/async) for a framework means both ways have to be implemented redundantly to avoid deadlock pitfalls and other async related concerns. What it also means that framework authors which haven't yet fully grabs the concept usually build the sync way first and the async way never really gets treated as a first class citizen. When going all in the patterns and practices of async become a first class citizen and get fully embraced. When the synchronization becomes part of the user code then the user is in control of deciding when to do what. Users can then decide to return Task.CompletedTask (Task is the new void) or to provide base class methods which are in their control.

Complexity, Maintenance cost, Burden for Contributors to contribute, cognitive overhead for reviewers etc is just not worth the benefits of having the sync and async way. I've been arguing for this for example in Marten. Jeremy wanted for legacy reasons to go the redundant way and they suffered through many bugs because of that. Microsoft ditched the sync way in the Azure SDK mostly as well because of those exact reasons. More frameworks and libraries will follow that approach. And yes occasionally one will get angry / snarky comments from users but hey: one can deal with that :)

Or to say it with the words of AsyncDouchebag

> Let's suffix everything with *Async cause you know: Task and Task<T> and ConfigureAwait(false) and await is not enough to see it is ASYNC!!!

https://twitter.com/asyncdouchebag/status/802288912244690944

> Let's suffix all methods like Async! FooAsync(), FooInt(), FooString(), FooBool(), FooBar() and FooIntAsync(), FooStringAsync()...

https://twitter.com/asyncdouchebag/status/802289421579997185

Have a great day all!

**Comment by veleek** [comment]
AsyncDouchbag -> followed. :)

Yup, I totally understand the argument and I can get onboard either way.  I just want to make sure that it's at least discussed and it's clear that 'everything' (yes, there will be exceptions) will be async.

You could even go as far as making certain properties (e.g. ActiveItem) async.  I'm not sure how serious I am about this proposal.  I just thought about it while writing this message.  The hacked up code below (runnable in Linqpad) shows how you could implement an 'asynchronous property'.  This also allows us to maintain the semantics where setting ActiveItem calls OnActivate, but a little bit more safely here.  Again, take this with a grain of salt, as I just threw it together as a test to see if it would work at all.  Could be more trouble than it's worth.

```csharp
async Task Main()
{
	Test t = new Test();
	t.Dump();
	t.Item = GetItem();
	
	object item = await t.Item;
	
	// Alternatively
	t.Item = Task.FromResult(new object());
	
	t.Dump();
}

public async Task<object> GetItem()
{
	await Task.Yield();
	return new object();
}

public class Test
{
	private Task<object> itemTask;
	public Task<object> Item
	{
		get { return this.itemTask; }
		set
		{
			itemTask = ((Func<Task<object>>)(async() => {
				var item = await value;
				await this.ActivateItem(item);
				return item;
			}))();
		}
	}
	
	public Task ActivateItem(object item)
	{
		return Task.CompletedTask;
	}
}
```

**Comment by nigel-sampson** [comment]
There will have to be some quasi sync inputs for things like bindings, this is why there's a property setter on  `ActiveItem` so when things like a list view or tab control change the selected item the `ActiveItem` is updated to reflect that.

Given the library will still be mixed mode (a lot of the methods in that Platform assembly dealing with the UI will stay that way) I'm more of the opinion that the `Async` suffix makes sense here.

I don't think there will be many places where we'll need both the sync and async overloads thankfully.

**Comment by danielmarbach** [comment]
> Given the library will still be mixed mode (a lot of the methods in that Platform assembly dealing with the UI will stay that way)

Can you elaborate a bit on this? 

any framework will have a combination of sync and async. A framework calls into the user code which it doesn't control entirely. From a framework perspective the key is to identify which parts can / should / or are allowed to call into IO bound code. This part should be designed for async. Since it is calling the user code it has to be async all the way on those paths. Everything else can and should be sync. 

If I get your point right you are saying your framework has UI centric extension points and those extensions are designed to be sync. When the screens, conductors etc call into user code this part interacts with user code which potentially calls into IO bound code and therefore should be async. So from that perspective you lean towards the async suffix? Did I get you right?

> Am 27.11.2016 um 21:22 schrieb Nigel Sampson <notifications@github.com>:
> 
> Given the library will still be mixed mode (a lot of the methods in that Platform assembly dealing with the UI will stay that way)

**Comment by nigel-sampson** [comment]
This is a subjective statement but outlines my reasoning. Libraries such as Octokit are around 90%+ async so dropping the naming convention doesn't lead to many surprises from the consuming developer.

Caliburn.Micro after all these changes will still have more synchronous methods than not so I lean towards the suffix for differentiation. 

Regarding the UI, you're correct that the UI will ultimately after to interact with the screens and conductors triggering async flows. I'd like to avoid async void but not sure it's going to be possible given these extension points include property setters triggered by bindings.

**Comment by RichiCoder1** [comment]
We use async for a lot of the under covers work in ChocolateyGUI, so I'd love to have first class-ish support in Caliburn. Let me know if and how I can help :)

**Comment by nigel-sampson** [comment]
Thinking about this in the last few days, going to need a lot more complexity in the various navigation services. Most of these fire a `Navigating` event with a `Cancel` property on the event args. If `IGuardClose` is made async then we'll be too late to actually cancel the navigation.

What we'd need to do is call the new async method. if the task is already completed then handle as is. Otherwise cancel the navigation immediately and then await the task. If it decides that we shouldn't cancel the navigation then call navigate on the service (skipping the guard close on the second run through).

This gets really messy when there are multiple view models all wanting to guard the close, I'd hate to see the whole loop above being run through multiple times.

**Comment by veleek** [comment]
Yeah unfortunately async doesn't really play well with events.  Just for my clarification, you're talking about the navigation service implementations within other frameworks not something specific within Caliburn right?  

I don't really like the solution that you proposed but I can't really think of anything better... maybe there will just be certain calls that need to remain synchronous.  Unfortunately lots of the lifecycle stuff tends to be tightly intertwined with navigation. :P

**Comment by danielmarbach** [comment]
Could you build an interop layer with TaskCompletionSources?

How about you create gists or tests of what problems you are currently facing and then we will chime in on those? Then we see a specific problem and can tinker with it without trying to build a most likely wrong mental model in our heads.

**Comment by veleek** [comment]
The problem is that the caller of the `.Navigating` event is the .NET framework, and since they're not aware that we're doing anything async the only real option is for the Caliburn code to block.  As soon as the event handler returns, the caller is going to continue.

**Comment by markgould** [comment]
Has any progress been made on this? I wouldn't mind helping out where possible. Still use CM in many projects, so async support would be nice to have.

**Comment by mms-** [comment]
Would be good to see this. Let me know how I can help.

**Comment by nigel-sampson** [comment]
Most of the interfaces on the `dev/4.0.0` branch are now converted across to be async and it's close to where I think we can do the next alpha.  

The bits left that can come in the next alpha are
- Window Manager
- Navigation Services
- Bootstrappers / Applications

Before we actually do the alpha I'd love for interested parties to check out the branch and have a play. One of the problems that contributed to this taking longer than hoped was getting confidence in consistent repeatable builds. Having others verify that they're having no build issues would be great.

Overall the journey to get there with the new project system was a bit of a journey but I'm happy to where we got to, however it does come with more breaking changes beyond just the async stuff.  These include

- Minimum version for Caliburn.Micro.Core upped to .NET standard 1.3
- Minimum version for Caliburn.Micro.Platform for WPF has been pushed to .NET Framework 4.6
- Minimum version for Caliburn.Micro.Platform for UWP has been pushed to 16299.
- We're now depending on Xamarin.Forms 3.0.0.561731.

Also assembly names are now related close to project name `Caliburn.Micro.Core` and `Caliburn.Micro.Platform`.

Having `Caliburn.Micro.Xamarin.Forms` as a separate package with it's own assembly and namespace I've come to the conclusion that this is failed experiment in over engineering to deal with having both Caliburn.Micro for Android while also supporting the Xamarin.Forms version at the same time.

By deprecating this assembly and collapsing back into Caliburn.Micro.Platform we can kill Platform.Core. Yay.

The samples have been updated to show some of this working.

Would love to get feedback.
