### ISSUE TITLE
Binding to action that is async Task doesn’t work

### ISSUE THREAD

**Issue by thavenPL** [Caliburn-Micro/Caliburn.Micro#428]
I got simple model class: 
```
    public class Model
    {
        public async Task OnLoaded()
        {
            await Task.Delay(1000);
        }

        public async Task DoWork ()
        {
            Console.WriteLine("Should show up in console");
        }
    }
```
OnLoaded is binded to Loaded event in window, and DoWork is binded to click event of button in this window. 

After press button nothing is writed to output. 

When i modyfi code to below:
```
    public class Model
    {
        public async void OnLoaded()
        {
            await Task.Delay(1000);
        }

        public async void DoWork ()
        {
            Console.WriteLine("Should show up in console");
        }
    }

```
then everything works fine. 

Version: 
"Caliburn.Micro" version="3.0.3" targetFramework="net452"
Caliburn.Micro.Core" version="3.0.3"  targetFramework="net452"

Sample project: 
[CaliburnMicroTest.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/954417/CaliburnMicroTest.zip)

**Comment by nigel-sampson** [comment]
The sample you've attached crashes on startup because the framework hasn't been initialised. Once that was done the above methods were called correctly.

I'd suggest looking at [this project](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/setup/Setup.WPF) for what a bare bones WPF project looks like with setup.
