### ISSUE TITLE
Syntax error in PropertyPath 'Unmatched parenthesis' in Data Grid

### ISSUE THREAD

**Issue by Raghava56** [Caliburn-Micro/Caliburn.Micro#479]
Hi,

I am binding my 'Data table' to data grid itemsSource.
if any column name contains either left or right parenthesis throwing some exception i.e
**An error occurred while dispatching a call to the UI Thread**  and from that column skipping remaining columns

How to handle these type of exceptions and How to skip these type of Columns from UI ?

Please give me any suggestion to handle these things.

Thanks and Regards,
Raghav

**Comment by nigel-sampson** [comment]
This sounds like an error with the `DataGrid`, can you expand on how this relates to Caliburn.Micro?

**Comment by Raghava56** [comment]
Hi,

This is wpf  (`DataGrid`) issue but not releated to Caliburn,Micro.
**Here is the Xaml Code**

    <DataGrid x:Name="bindedItems" Grid.Row="1" ItemsSource="{Binding BindedItems}" SelectionMode="Extended"/>

**Here is the C# Code**

    this.BindedItems = new DataTable();
    this.BindedItems = table;

table columns are like this

**Right Parenthesis)**

**testing**

**Lest Parenthesis(**


Can you know then only give me any suggestion how to handle these type of things

Thanks and Regards,
Raghav

**Comment by mvermef** [comment]
Your question probably belongs on stackoverflow since it's unrelated to CM. I suspect your creation of the DataTable to be the cause.  I would also suggest not using DataTable since that like .Net 1.0 code, wasnt intended to be used with WPF,  observablecollection or a straight `list<your type>` to define your grid...

The code that initializes you BindedItems just looks weird to be honest. Assigning "table" alone will set the property assuming "table" is already filled...

**Comment by nigel-sampson** [comment]
Thanks @mvermef, I'd suggest Stack Overflow as well.
