### ISSUE TITLE
Cant get text from passwordbox

### ISSUE THREAD

**Issue by crazypigs** [Caliburn-Micro/Caliburn.Micro#487]
I was following the example from their website but the passwordbox just returns an empty string. Why is this?

**Comment by nigel-sampson** [comment]
You'll need to elaborate here, which platform are you on and provide some of your code.

**Comment by crazypigs** [comment]
sorry.  I asked it on [stack](https://stackoverflow.com/questions/47025669/why-does-the-caliburn-micro-explanation-not-work/47026150#47026150) a while back too.

**Comment by nigel-sampson** [comment]
There's definitely something funky going on, need to look into it some more.

**Comment by mvermef** [comment]
If I remember correctly you couldn't bind to this because the passwordbox doesn't have a dependency property, the only place it worked correctly was winRT or silverlight. 

Therefore the only way I remember to do this was with an attached helper property or creating your own, since it's sealed. Or responding with the changed event thru `Attached` and setting your password property with that of the pwb.password property, convention will not work here. 

Probably the best thread, unrelated to CM but Mvvm holds true

**Comment by nigel-sampson** [comment]
That makes sense, looking at the [`ConventionManager`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L250) it seems the example on the front page works on UWP and Silverlight but not WPF.

If you create your own attached property like the @mvermef suggests then you could then update the convention to use your property.

**Comment by nigel-sampson** [comment]
Had a bit of a play with your sample (thank you for that by the way) I had some mixed success. With out of the box attached dependency properties such as `Grid.Row` you can get it to work altering the convention to something like

``` csharp
ConventionManager.AddElementConvention<PasswordBox>(PasswordBoxHelper.PasswordProperty, "(Grid.Row)", "PasswordChanged");
```
However switching the second parameter to "(PasswordHelper.Password)" doesn't work. The problem here is that the xaml parser has no namespace or notion of that that type when we're dealing with strings.

This got me thinking about whether there was an in the box attached property we could abuse to store the password, then remembered about the `FrameworkElement.Tag` property.

We can modify your helper to store the password in the tag (this will remove the need for the `Password` attached dependency property.

``` csharp
private static void OnPasswordChanged(object sender, RoutedEventArgs e)
{
    PasswordBox passwordBox = sender as PasswordBox;

    passwordBox.Tag = passwordBox.Password;
}
```

the convention then becomes
``` csharp
ConventionManager.AddElementConvention<PasswordBox>(FrameworkElement.TagProperty, "Tag", "PasswordChanged");
```

which works for both binding and and parameter.

**Comment by yuzifu** [comment]
> Had a bit of a play with your sample (thank you for that by the way) I had some mixed success. With out of the box attached dependency properties such as `Grid.Row` you can get it to work altering the convention to something like
> 
> ```cs
> ConventionManager.AddElementConvention<PasswordBox>(PasswordBoxHelper.PasswordProperty, "(Grid.Row)", "PasswordChanged");
> ```
> 
> However switching the second parameter to "(PasswordHelper.Password)" doesn't work. The problem here is that the xaml parser has no namespace or notion of that that type when we're dealing with strings.
> 
> This got me thinking about whether there was an in the box attached property we could abuse to store the password, then remembered about the `FrameworkElement.Tag` property.
> 
> We can modify your helper to store the password in the tag (this will remove the need for the `Password` attached dependency property.
> 
> ```cs
> private static void OnPasswordChanged(object sender, RoutedEventArgs e)
> {
>     PasswordBox passwordBox = sender as PasswordBox;
> 
>     passwordBox.Tag = passwordBox.Password;
> }
> ```
> 
> the convention then becomes
> 
> ```cs
> ConventionManager.AddElementConvention<PasswordBox>(FrameworkElement.TagProperty, "Tag", "PasswordChanged");
> ```
> 
> which works for both binding and and parameter.

I store the password in the Tag property of the PasswordBox according to your method, so that the password value can be synchronized to the ViewModel property when change on UI. But after doing this, there is a problem: change the value of the property in the ViewModel, it can not be synchronized to UI, like in the initialization.

**Comment by nigel-sampson** [comment]
You'll need to extend to attached property events above so that changes to the `Tag` property is synced back into the `Password`.
