### ISSUE TITLE
Caliburn.Micro & Xamarin Live Player

### ISSUE THREAD

**Issue by CesareVin** [Caliburn-Micro/Caliburn.Micro#499]
I all,
i'm trying to use Caliburn.Micro in a Xamarin.Forms app that i would like to test with Xamarin Live Player but without success.
First of all trying to launch app i found an error, seem that Xamarin Live Player needs a default constructor for App class, 
` Level=Error, Title=Visualization Error, Message=Cannot find a default constructor for XXXX.App (NInterpretException)]`
Adding a default constructor for App class fix the error but i'm only able too see a blank view and it makes sense because Caliburn.Micro container is not correctly initialized and 
` DisplayRootView<HomeView>();` is never called.
Some suggestions on how I could proceed to have Live Player working with Caliburn.Micro scenario?
Thanks in advance.

**Comment by nigel-sampson** [comment]
I haven't tried it with the Live Player. 

Can you try adding a call to `Initialize` to your parameterless consructor.?

**Comment by godrose** [comment]
@nigel-sampson  I have the same issue. It looks like a showstopper.
The live player seems to be using the `Activator`  with no support for IoC/DI/anything that possesses injection capabilities. Moreover adding an explicit method called Initialize/Start/Run/whatever doesn't help either because the base constructor of `FormsApplication` is already called.
I don't really see how this limitation can be overcome. There needs to be some kind of bridge with deferred initialization for `FormsApplication` to make this work.

**Comment by mvermef** [comment]
Known issue for live player related to di and reflection

On Jan 14, 2018 11:23 AM, "Gennady Verdel" <notifications@github.com> wrote:

@nigel-sampson <https://github.com/nigel-sampson> I have the same issue. It
looks like a showstopper.
The live player seems to be using the Activator with no support for
IoC/DI/anything that possesses injection capabilities. Moreover adding an
explicit method called Initialize/Start/Run/whatever doesn't help either
because the base constructor of FormsApplication is already called.
I don't really see how this limitation can be overcome. There needs to be
some kind of bridge with deferred initialization for FormsApplication to
make this work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Caliburn-Micro/Caliburn.Micro/issues/499#issuecomment-357530947>,
or mute the thread

**Comment by nigel-sampson** [comment]
Is there a link to where the known issue is documented @mvermef ?

**Comment by mvermef** [comment]
let me see if I can find the entry, I was the one that reported to xamarin..

**Comment by godrose** [comment]
> looks like the already pushed a new update but not sure if it was related to this bug. The bug report I had was closed. Then again it might be a issue with CM and PCL. My issue was related to DI but .net core, the error is posting appears to be an error with iOS flavor of the Live PLayer

I tried with the latest version of the player for Android Platform and .NETStandard shared code.
No luck for me...

**Comment by vb2ae** [comment]
Xamarin Live player was discontinued so this bug should be closed
