### ISSUE TITLE
Multiple instances of same view model, with same view

### ISSUE THREAD

**Issue by LimpingBear** [Caliburn-Micro/Caliburn.Micro#516]
I am trying to bind the same instance of a view model in two places with the same view. Only the instance rendered last is shown. The following xaml replicates the issue.

`            <GroupBox Header="1" Grid.Column="0" Grid.Row="0">`
`                <ContentControl cm:View.Context="Test" cm:View.Model="{Binding TestViewModel}"/>`
            `</GroupBox>`
            `<GroupBox Header="2" Grid.Column="0" Grid.Row="1">`
                `<ContentControl cm:View.Context="Test" cm:View.Model="{Binding TestViewModel}"/>`
`            </GroupBox>`

The content of GroupBox 2 is rendered correctly.
The content of GroupBox 1 is blank

**Comment by godrose** [comment]
@LimpingBear Is that supposed to work? I wonder what is the real-world scenario where you would have such requirement.

**Comment by nigel-sampson** [comment]
What type does `TestViewModel` inherit from.

My guess is that the normal view resuse code in the framework is getting in the way here (it's certainly a novel problem).

**Comment by LimpingBear** [comment]
`TestViewModel` inherits `IConductor, IScreen, IChild, IParent, Conductor<T>.Collection.AllActive`.

I found an old [issue](https://github.com/Caliburn-Micro/Caliburn.Micro/issues/195) that dealt with, what I think is the same problem, but there was no real solution. 

The scenario is that the TestViewModel is shown in a part of the main window and also in a separate window. Multiple different instances of TestViewModel are open at the same time, that are for example moved to a secondary display and on the primary display you have the main window but can also do things with the TestViewModel

**Comment by nigel-sampson** [comment]
Internally when the framework tries to locate the view for a view model it first checks to see if the view model is `IViewAware`, if so it asks the view model if a view already exists and tries to reuse that.

The use case for this is view models that are coming and going from their parent view, so this saves time on recreating / rebinding the view.

In your case what's happening is that Group Box 2 is trying to reuse the view from Group Box 1, since a view can't be in two places at the same time it's remove from 1.

There a few ways we can work around this:

1. Inherit from a view model that's not `IViewAware`, given you're inheriting from `Conductor` this probably isn't a viable solution.
2. Overide `GetView` to return `null` on your view model. This will force the framework to create a new view for Group Box 2.

Hope this helps.

**Comment by LimpingBear** [comment]
Overriding `GetView` solved my problem. Thanks for the explanation and the help
