### ISSUE TITLE
What's the purpose of context argument in Delegate Result?

### ISSUE THREAD

**Issue by albertodepena** [Caliburn-Micro/Caliburn.Micro#525]
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/DelegateResult.cs

Is that by design?

Thanks =)

**Comment by nigel-sampson** [comment]
The context is provided to all coroutines by design. It should be passed in by the framework so you shouldn't need to worry about it. 

Some people who use coroutines make use of things like the view from the context. This allows the custom result to encapsulate some work which touches the UI from the view models.
