### ISSUE TITLE
cannot find view for XXXViewmodel

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#538]
hi,i used caliburn.micro in WPF,and i cannot find the view wtih different Assembly 
project Viewmodels\VM\MainViewModel
project Views\MainView
viewmodel and view in different Assembly ,plz help 
btw ,i try the override "IEnumerable<Assembly> SelectAssemblies()" in AppBootstrapper,but cannot work

**Comment by nigel-sampson** [comment]
The difference is the VM folder there. 

If you have a view model with a full type name of `Project.ViewModels.VM.MainViewModel` the view it look for is `Project.Views.VM.MainView`.

**Comment by hjj28810** [comment]
i means viewmodels and views are in different project 
projectA Core/ViewModels/MainViewModel
projectB CRM/VIews/MainView
and i try this "var views = ViewLocator.TransformName("Core.ViewModels.MainViewModel", null);"
2 string in this list ,"Core.Views.MainView","Core.ViewModels.MainView",
so the vm and view must be in the same project?

**Comment by nigel-sampson** [comment]
They don't have to be in the same project, but their `Type.FullName` has to follow the conventions has before.  

The sample from your first post differed due to the VM folder.

In your second sample it's due to that root namespace. If you want to override the conventions you can with. There's a sample in my [NDC Sydney 2016](https://github.com/nigel-sampson/talks/blob/master/ndc-sydney-2016/NDC.Build.App.UWP/App.xaml.cs#L28).

**Comment by hjj28810** [comment]
ok，thx，i solved
