### ISSUE TITLE
Any list or collection which support the Data Virtualization in Caliburn.Micro?

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#543]
use the BindableCollection can implements  Data Virtualization?

**Comment by mvermef** [comment]
that collection can not.

**Comment by hjj28810** [comment]
which one can？

**Comment by mvermef** [comment]
what platform are you targeting

**Comment by nigel-sampson** [comment]
I assume by virtualization you're talking about a "load more" scenario when the UI gets the bottom of the list. How that virtualization is done depends a lot on the UI control doing it, typically they have their own interfaces to implement. 

`BindableCollection` in CM implements all these interfaces it can including `INotifyCollectionChanged` and `INotifyPropertyChanged`, but wiring that into the UI for the virtualization will depend on the vendor of the control.

**Comment by Yeah69** [comment]
I know it is a common pattern in web applications to use "load more"-scenarios. However, please don't ever use such a pattern on desktop or mobile applications. It's cringe-worthy. A moderate data virtualizing solution will implement IList. Hence, it has a Count property and an indexer. So controls (such as the ListBox or DataGrid) would assume that the whole list is actually there and adjust the scrollbar accordingly while behind the certains the data virtualizing solution would load the data on demand and page-wise. The result is that the user wouldn't know the difference.

**Comment by hjj28810** [comment]
i use the Data Virtualizing on WPF

**Comment by hjj28810** [comment]
and the Data Virtualizing not only Load More, its good to manage the memory when big-data without paging

**Comment by nigel-sampson** [comment]
A lot of applications make use of data virtualization and its certainly not "cringe worthy" if done correctly. The Twitter timeline is a prime example, as the control nears the end of the list it signals that more should be loaded by the view model. 

Obviously the implications and the how its applied completely depend on the UI control in question and whether it supports virtualization.

**Comment by Yeah69** [comment]
First of all, I did not say data virtualization in general is cringe worthy (your response kind of implies that). We are talking about two very different kinds of data virtualization here: "load more" data virtualization and "emulating the whole huge list, but only loading the items which are demaded at the moment by the indexer" data virtualization. The second kind has the ability to calculate the count of elements in the data virtualized list. Hence, controls like the ListBox or the DataGrid can calculate the ScrollBar-Values (max value and current position) correctly. So the user would not notice any difference, but in the background the data virtualized list would only load the elements which are positioned where the user scrolled to and not the whole list.
The typical **desktop** application would be a LOB-style (line of business) application. If such an application is backed by a DB with like 100.000 rows you wouldn't want to load all this 100.000 rows in your memory, especially not if your ViewModels representing the rows are not in DTO-style (data transfer object). However, if you implement the "load more" solution in this case and lets assume a page-size of 100, then the user would need to scroll a thousand times to the end of the list in order to get to the last row. That exactly is cringe worthy, because with the second kind of data virtualization you wouldn't have this problem at all. If you want to try the second kind, then see in the link which I posted earlier.

Your prime example is a **web** application. I did mention that it is common for web application to use "load more" systems. Also applications like twitter often generate "endless" content suggestion streams. The count of elements in this kind of data virtualized list would be infinity. You cannot calculate the last position for all (infinite) elements. Hence, you cannot apply the second kind of data virtualization which I mentioned before here. Whole different use case. Of course, using "load more" for specifically this use case is not cringe worthy.
