### ISSUE TITLE
How to close Screen?

### ISSUE THREAD

**Issue by dmitriy-shleht** [Caliburn-Micro/Caliburn.Micro#554]
**Simplified view - TestView**
```
<ContentControl x:Name="ActiveItem" Grid.Row="0" />
<ContentControl x:Name="DialogView" Grid.Row="1" />
```

**ViewModel**
```
public class TestViewModel : Conductor<IScreen>
    {
        private readonly Test2ViewModel test = new Test2ViewModel();
        private IScreen _dialogView;

        public IScreen DialogView
        {
            get { return _dialogView; }
            set { _dialogView = value; NotifyOfPropertyChange(() => DialogView); }
        }

        public void OpenTest2()
        {
            DialogView = test;
        }

....
    }
```

**Test2View**
```
<Button x:Name="TryClose" Content="Close" />
```
I tried different ways, but the view doesn't close. If I use the standard `ActivateItem(test)` activation method, then TryClose works.
But I can't use `ActivateItem(test)`, because I already have `<ContentControl x: Name = "ActiveItem" />` on `TestView`. I need to display multiple `ContentControl` in different places `TestView`.

**Comment by coczero** [comment]
The `x:Name` binding only works if the view has been correctly connected to Caliburn which is done by using `ActivateItem`. What you could do is it add `cal:Bind.Model={Binding}` to the Button to manually connect it to the ViewModel. Then the `x:Name` binding will work.

**Comment by dmitriy-shleht** [comment]
No problem is in the method call. The method is invoked, but the UserControl inherited from the screen is not closed.

**Comment by dmitriy-shleht** [comment]
[Setup.WPF.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/2535066/Setup.WPF.zip)
Please see an example.

**Comment by coczero** [comment]
Well thats not how it works. A TryClose closes the corresponding window for a ViewModel For example if you use the `WindowManager` to show the view of a ViewModel. `TryClose` doesn't "remove" the current Screen from the ContentControl nor does it switch back to the previous view.

**Comment by dmitriy-shleht** [comment]
How can it be closed without using `WindowManager`?

**Comment by coczero** [comment]
Your conductor needs to be the one who activates and deactivates items. Therefore if you want to "Close" (change to a different Item) you will have to do that in your Shell2ViewModel by calling ActivateItem. You could use an event in your Test2ViewModel which notifies your Shell2ViewModel that it should switch to a different Screen.

**Comment by dmitriy-shleht** [comment]
Cannot use one `ActivateItem` because I have to have several screens on the view

This is what my structure actually looks like.
https://stackoverflow.com/questions/20607168/can-anybody-provide-any-simple-working-example-of-the-conductort-collection-al/21639773#21639773

**Comment by nigel-sampson** [comment]
The conductor will close the child view model correctly here, but it' won't null the `DialogView` property, so you'd still end up displaying the closed view.

What I'd do is instead of closing at the child level is "bubble" the close message up to the conductor and then it can handle the child conductor correctly. In your simple example that would be setting the bound property to null, or in the more complex collection example it would be removing it from the collection.

**Comment by dmitriy-shleht** [comment]
Something I do not understand you. Can you show how to do this with my example?
[Setup.WPF.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/2535066/Setup.WPF.zip)

**Comment by nigel-sampson** [comment]
Your sample had a number of problems.

1. When you try to close an child view model being conducted by a parent conductor it will pass the close up to the conductor. However you weren't actually using the conductor at all.

Having the following will ensure that the child view model has a relationship to it's parent conductor.
``` csharp
public void OpenTest2()
{
    ActivateItem(test);
    DialogView = test;
}
```

2. As mentioned because you're using a custom property on the conductor that's not being "unset" on close you'll need to do that yourself. The following does that.

``` csharp
public TestViewModel()
{
    test.Deactivated += (s, e) =>
    {
        if (e.WasClosed)
        {
            DialogView = null;
        }
    };
}
```
