### ISSUE TITLE
Can't get the samples compile

### ISSUE THREAD

**Issue by garnbleiche** [Caliburn-Micro/Caliburn.Micro#587]
I tried to compile the sample "Features.WPF" but get a lot of errors. 

I added caliburn.micro nuget package but can't compile.

![devenv_2019-03-02_10-24-14](https://user-images.githubusercontent.com/28215618/53680025-7cbd6b80-3cd5-11e9-8f5b-57f8087556da.png)

**Comment by nigel-sampson** [comment]
The `Features` projects use the build output from the main solution , if you've just pulled down a new version you'll want to rebuild the main solution first.

**Comment by mjfreelancing** [comment]
I am also having troubles. I have attempted to build the main solution but it fails with errors.

![Capture](https://user-images.githubusercontent.com/17043225/55288748-c483ff80-5407-11e9-8f84-8b6655dedf8b.JPG)

Any ideas?

I'm completely new to UWP and Caliburn.Micro so I'm hoping there is an easy fix.

**Comment by nigel-sampson** [comment]
What's the full name of the build task that's failing?

**Comment by mjfreelancing** [comment]
I'm not sure if this is what you want. It's the only other info I can see:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.Messaging.targets(41,3): warning VSX1000: No enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The project 'Caliburn.Micro.Core' will continue building offline

If you require something else please let me know where to get it from.

**Comment by nigel-sampson** [comment]
That one should be ok. it's just listed as a warning and you should be able to continue with that. 

The second line has the build task cut off by the screenshot "Microsoft.Build.Tasks.Git...

I'm curious what the rest of that is.

**Comment by mjfreelancing** [comment]
Full screen shots:

 



 

1>------ Rebuild All started: Project: Caliburn.Micro.Core, Configuration: Debug Any CPU ------

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.Messaging.targets(41,3): warning VSX1000: No enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The project 'Caliburn.Micro.Core' will continue building offline

 

1>Done building project "Caliburn.Micro.Core.csproj".

1>C:\Users\Malcolm\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(20,5): error : Unable to locate repository containing directory 'C:\Data\Dev Playground\Caliburn.Micro\Caliburn.Micro-master\src\Caliburn.Micro.Core'.

1>Done building project "Caliburn.Micro.Core.csproj" -- FAILED.

 

(multiples of)

 

Is there anywhere else I can get further detail from?

 

I asked a colleague to download and build and he could not either.

 

Malcolm Smith

**Comment by nigel-sampson** [comment]
Ah, did you do a download of the source or a git clone?

**Comment by mjfreelancing** [comment]
Download

**Comment by nigel-sampson** [comment]
I suspect that's why, I use [Git Versioning](https://github.com/AArnott/Nerdbank.GitVersioning) which probably isn't liking that it's not in a git repo.

**Comment by mjfreelancing** [comment]
ok, a clone solved the issue of building the main project but the /features solution will not build now. It's complaining about some Android features not being installed. The prompt indicates to double click the message and follow the prompts but I don't get anything. As I'm only interested in UWP I tried unloading the Android related portions but am still having issues.

Do you know what Android features I may need to install? I currently have levels 26 and 27 of the SDK installed but don't know what else to look for (I don't do mobile dev).

**Comment by nigel-sampson** [comment]
Not off the top of my head (at work), surprised that unloading didn't work.

Tried setting them to not build in "Build Configuration"?

**Comment by mjfreelancing** [comment]
I just reverted the repo and tried again after unloading everything other than the UWP project. It's complaining about broken references to the Caliburn.Micro.Core and Platform. I updated these to point the DLL in my local folder after a clean rebuild of the main project:

\Caliburn.Micro\bin\Caliburn.Micro.Platform\debug\netstandard2.0

(I'm guessing this is the correct version to use)

After doing that I now get the following errors:

![image](https://user-images.githubusercontent.com/17043225/55299436-b91feb00-547e-11e9-9374-2c6e01b883b9.png)

Have a linked to the wrong assemblies?

**Comment by nigel-sampson** [comment]
The Features project should already be set up to use the correct build output from the main projects, so there shouldn't be a problem there.

Did you unload the shared project that had the view models?

The CI pipeline builds the samples on every build and that's being going well.

**Comment by mjfreelancing** [comment]
This shows what I unloaded:

![image](https://user-images.githubusercontent.com/17043225/55299658-9b06ba80-547f-11e9-8eea-6bd7cf17cd29.png)

I reverted again to show the error (there's heaps of build errors related to this)

![image](https://user-images.githubusercontent.com/17043225/55299717-eb7e1800-547f-11e9-80de-a8a0bcd0aad1.png)

**Comment by mjfreelancing** [comment]
Have you tried this against a fresh clone rather than your existing build environment? I've asked some other people to try and nobody can get the samples to build.

**Comment by nigel-sampson** [comment]
I haven't for a while, but this is why it's part of the build pipeline, I don't release the package unless the samples build against it.

**Comment by mjfreelancing** [comment]
Well I don't know what to say. As you can see in the screen shots I provided it cannot find the assemblies when building a fresh clone (and it isn't just my environment).I'd I delete the references which folder should I use to add them back in myself?On Apr 3, 2019 13:54, Nigel Sampson <notifications@github.com> wrote:I haven't for a while, but this is why it's part of the build pipeline, I don't release the package unless the samples build against it.

**Comment by nigel-sampson** [comment]
Can you share the output path the build from the main project is being sent to and the path the features project is looking for the assemblies?

**Comment by mjfreelancing** [comment]
I worked out the issue. The main project builds the debug release out of the project (which was fine for my needs) but the Features project references the release version of the assemblies.

After I built the release version of the main project the references are now sorted and I can run the sample app.

**Comment by nigel-sampson** [comment]
Excellent
