### ISSUE TITLE
BootstrapperBase does not exist in 4.0.63

### ISSUE THREAD

**Issue by MSiffert** [Caliburn-Micro/Caliburn.Micro#600]
I am trying to develop a WPF application using .NET Core (3.0). So I installed Caliburn.Micro from 4.0.62 because this version targets .NET Standard.
But it seems like `BootstrapperBase` does not exist anymore. I haven't seen anything regarding BootstrapperBase in the docs nor the release notes.
Did I miss something?

**Comment by mvermef** [comment]
Bootstrapper does exist but it was targeting NET46 which is straight .Net Framework, Target compilation is occurring within the Directory.Build.Targets it tells the compiler / visual studio to more or less ignore the contents of that folder which contains the BootstrapperBase.cs and other code associated due to Platform segregations, until CM is updated to incorporate those features of .NET Core 3 you won't see BootstrapperBase available at this time.

**Comment by nigel-sampson** [comment]
At the moment I haven't added the changes needed to support .NET Core 3.

**Comment by dhhunter** [comment]
Good work on the Project!  I know you have a lot of work to do and very little free time to do it in; however, I would like to second the motion to have Caliburn.Micro support .NET Core 3.0!  

I am about to start a new Windows Desktop Project and I would really like to target .NET Core from the beginning so that I can leverage the power of C# 8 as well as multitude of other benefits of adopting .NET Core.  I am primarily a back end guy and have very little UI experience, what little I do have (outside of WinForms) was using Aurelia, so I believe CM might be the most comfortable choice for me.

Thank you for all of your hard work in supporting the project!

**Comment by Rmurray0809** [comment]
I'm still fiddling with it but I downloaded the source and just swapped the target over to Core 3.0, add the desktop app nuget and change one line of code in the ActionMessage.cs class (an ifdef targeting NET to NET || NETCOREAPP3_0).  It complains about the Xaml Behaviors nuget but builds.  

The tests don't properly run for the platform but looking around that may be an issue with .net Core 3.0 at the moment.  There is discussion about this in the Xaml Behaviors GitHub and indicates that the core team is aware and working on it.

Unfortunately I don't have any experience with multi-targeting builds so I'm hesitant to say I haven't absolute broken everything in the project files getting when I was trying to get it to load in VS2019.

**Comment by nigel-sampson** [comment]
Nicely done.  The multi-targeting shouldn't be too bad, take a look through the [project file](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj) and see where `net45` is referenced and duplicate with `netcoreapp3.0`.

You could duplicate the definition of NET across both platforms by messing with the [Directory.Build.targets](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Directory.Build.targets).

**Comment by nigel-sampson** [comment]
.NET Core 3 support has been merged and available in the MyGet feed, would appreciate some eyes on it.
