### ISSUE TITLE
Question about DisplayRootViewForAsync

### ISSUE THREAD

**Issue by cbfrank** [Caliburn-Micro/Caliburn.Micro#622]
Hello
in the source code of DisplayRootView, it first creates a navigate page as the main page of the app, and then navigates to the view that should be shown.
but in the source code of DisplayRootViewForAsync, it creates the view and set it as the main page of the app directly? Why does it not follow the same pattern of DisplayRootView which set navigate page as the main page of the app?

thanks

**Comment by nigel-sampson** [comment]
`DisplayRootViewForAsync` first creates the view model and sets the main page to the view more that view model. This is major difference between "view first" and "view model" first.

In "view first" we're telling the navigation page to navigate to a new view and then building a view model from the view change.

"view model first" is the reverse, we start with a view model and go from there. This is typically used where the main view shouldn't be a navigation page but some sort of shell view. This is more common in desktop applications rather than mobile.

**Comment by cbfrank** [comment]
it's clear to me. Thank you!

**Comment by nigel-sampson** [comment]
No worries.
