### ISSUE TITLE
Unexpected behaviour of ChangeActiveItem - previous item doesn't get closed

### ISSUE THREAD

**Issue by HuggerCoursera** [Caliburn-Micro/Caliburn.Micro#629]
I've found that Conductor<object>.Collection.OneActive actually doesn't remove deactivated screen from conducted items collection on using ChangeActiveItem with parameter closePrevious:=true. At the same time if I call DeactivateItem(ActiveItem, true) and after that ActivateItem(new SomeViewModel()) then previous item do become removed from conductor's items list. Is it a known bug or some expected behaviour and misuse of conductor by me? Thank you in advance for explanation.

**Comment by mvermef** [comment]
What version are you using?

**Comment by HuggerCoursera** [comment]
> What version are you using? Can you show us a code snippet of your use?

I've set up a [demo project](https://github.com/HuggerCoursera/CMChangeActiveItemIssueDemo) to show the issue. Caliburn.Micro's version 3.2.0.

**Comment by mvermef** [comment]
The way I am looking at this is that each time you activate the shell designed with 1 Active screen at any given time, then you are expecting the premise that when that screen is deactivated then it will be popped off the Item collection as long as the close = "false", correct?  Do you actually want `FirstNestedUserControlViewModel`  gone? 

One of the things I always did with Aggregator was to give the item being passed via an event some details so we know how to handle that in the collection.  Since you are giving it `SomeProperty` and no value other than 0, that message is sort of wasted.  I would use it to your advantage. 

That being said.  I don't believe you were getting the expected behavior due to calling the wrong class object type to be removed.  

` ChangeActiveItem(Items.OfType<SecondNestedUserControlViewModel>().First(), true);` works.

**Comment by HuggerCoursera** [comment]
> You might have found a bug in 3.2

Thank you for taking time to look into this matter
