### ISSUE TITLE
Inconsistent behavior of navigation with WithParam

### ISSUE THREAD

**Issue by ykydaird13** [Caliburn-Micro/Caliburn.Micro#630]
I am coding a UWP app with Caliburn.Micro 4.0.89 now. When I navigate to another page with parameters, some parameter is passed correctly and others not. For example, I will receive a correct string and a null BindableCollection<Scan> when I am sending them at the same time(which are assigned).

For demo:https://github.com/ykydaird13/cm-bugdemo1
ps: project is built with vs2019 and SDK for Windows 10 1903

I navigate with following codes:
```C#
navigationService.For<SecondPageViewModel>()
                .WithParam(l => l.Scans, Scans)
                .WithParam(l=> l.Msg,Msg)
                .Navigate();
```

definition:
```C#
private BindableCollection<Scan> scans;
public BindableCollection<Scan> Scans
{
	get { return scans; }
	set { Set(ref scans, value); }
}
private string msg;
public string Msg
{
	get { return msg; }
	set { Set(ref msg, value); }
}

public class Scan : PropertyChangedBase
{
	private string scanId;
	public string ScanId
	{
		get { return scanId; }
		set { Set(ref scanId, value); }
	}
	private Uri image;
	public Uri Image
	{
		get { return image; }
		set { Set(ref image, value); }
	}
	public Scan(string scanid, string path)
	{
		ScanId = scanid;
		path = System.IO.Path.Combine(Environment.CurrentDirectory, "Image", path);
		Image = new Uri(path);
	}
}
```

**Comment by nigel-sampson** [comment]
This is because of the design of the `Frame` control in UWP. When you're saving and restoring frame state it tries to serialize navigation arguments to a custom format which if the argument is a custom type will throw an exception.

In order to work around this in UWP that arguments are built into a url query string which can be serialised. Hence string working and not the collection.
