### ISSUE TITLE
Seeking clarity on update to .NET Core 3

### ISSUE THREAD

**Issue by dbruning** [Caliburn-Micro/Caliburn.Micro#655]
Hi, firstly thanks for your work on this project!
I have a WPF application that is using an earlier version of Caliburn.Micro against the dotnet framework. The app is due for a big update and I’m considering moving to dotnet core but I’m not clear on the support for core in Caliburn.
#608 indicates that Caliburn version 4 (currently in alpha) has support for dotnet core 3. Is there any support for dotnet core 3 in earlier (non-alpha) versions of Caliburn? Alternatively - do you have any timeline for when Caliburn 4 is likely to move out of alpha? Thanks.

**Comment by nigel-sampson** [comment]
At the moment it’s just the alpha, no firm date at the moment.

**Comment by michaelkollmann** [comment]
Any update on when it will move out of alpha?

**Comment by nigel-sampson** [comment]
My biggest concern is that because I'm not actively doing app development these days I don't have a high degree of confidence in the alpha in terms of gathering feedback.  We've had about 200 ish downloads of alpha builds but no feedback.

**Comment by michaelkollmann** [comment]
Yeah, I understand that. 
But no feedback also means that nobody complained so maybe it's all good?
Kidding aside, I have just upgraded one of our company internal software tools (written in .NET 4.6) to the latest Caliburn.Micro Alpha.

The upgrade itself was easy enough and everything seems to be running just fine. 
I'll let you know if everything is going well in the next weeks.

**Comment by nigel-sampson** [comment]
Thank you for the information.

**Comment by beachwalker** [comment]
Hi, I converted an app with many screens. Works but the change to async costs some effort. Did not find many bugs. If you want to get more feedback you should open the published "alphas" to a bigger audience -> just publish to nuget also, the configuration of myget etc. is extra effort and you have to know it. Currently the version in myget (what I used) is newer. The problem is that the switch to Async is mixed up with the Net Core switch. Otherwise the pain would be much less, what do you think?

**Comment by nigel-sampson** [comment]
There is an recent beta on the proper nuget feed with .net core support.
