### ISSUE TITLE
Back button handling seems to be broken for WP8.1

### ISSUE THREAD

**Issue by agibalov** [Caliburn-Micro/Caliburn.Micro#74]
For some reason, the same page gets duplicated on the backstack. Here's what I do:
1. Get [CM.HelloUniversal](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/CM.HelloUniversal) app (as of e8a75edc65c8a2818fc0b2598f72ac8ad31541c3)
2. Add Caliburn.Micro NuGet package to WindowsPhone project (Caliburn.Micro 2.0.0)
3. Build

Now, the magic:
1. Run the app from VS
2. App launches, everything is fine
3. Tap Back button
4. Everything is fine so far
5. Run the app from the list of installed apps
6. App launches, everything is fine
7. **Tap Back button**
8. **The app page is closed, but another instance appears immediately**
9. Tap Back button
10. The app is closed

I've also recorded a video: http://www.youtube.com/watch?v=HGnS2W7O8e0

**Comment by loki2302** [comment]
After gitcloning the recent version of samples and adding 2.0.1 as a dependency, I still see that CM.HelloUniversal behaves the way I originally described. Are there any plans to fix it? I'd love to help, but this bug is actually a showstopper for my very first WP8.1 hello world (for half a year already).

**Comment by nigel-sampson** [comment]
That's bloody weird, I haven't been able to recreate it as per the video, however I did manage to create  about 10% of the time when using the start button to exit the app. Double weird was that attaching the debugger meant it always worked correctly.

I've tried a different approach in https://github.com/Caliburn-Micro/Caliburn.Micro/commit/b84c15c8071eb098d295949a21262c425082e4d4 and can't recreate since.
