### ISSUE TITLE
Resharper and Property Changed Notification snippet

### ISSUE THREAD

**Issue by schovan** [Caliburn-Micro/Caliburn.Micro#740]
ReSharper helps implement property change notification for Caliburn Micro 3.2.0 from nuget.
https://www.jetbrains.com/help/resharper/Coding_Assistance__INotifyPropertyChanged_Support.html

![image](https://user-images.githubusercontent.com/16373322/108556129-d2daad80-72f6-11eb-91f6-6adb743b5475.png)

This feature doesn't work for 4.0.161-rc from myget. Maybe because it is not .Net Framework, but .Net Standard.
Is there any trick how to make it working? Will this feature be officialy supported in version 4?

**Comment by muntablues** [comment]
This is really a big loss for me as well. I checked the difference between the versions and cannot find any big difference...

I also started a ticket at jetbrain but there is no progress since 5 month! See: https://resharper-support.jetbrains.com/hc/en-us/community/posts/360009906719 

Maybe some of the guys here has an idea how to solve :-)

**Comment by vb2ae** [comment]
@schovan @muntablues  A fix should be available with the next version of JetBrains.ExternalAnnotations package

[https://youtrack.jetbrains.com/issue/RSRP-482219?_ga=2.22690931.918464377.1619136499-1204162761.1615477180](https://youtrack.jetbrains.com/issue/RSRP-482219?_ga=2.22690931.918464377.1619136499-1204162761.1615477180)

**Comment by vb2ae** [comment]
This can be closed
