### ISSUE TITLE
ActivateItemAsync don´t work over Dependency Injection

### ISSUE THREAD

**Issue by lgund** [Caliburn-Micro/Caliburn.Micro#769]
Description
===========
I am trying to create a button which could change ContentControl View via `ActivateItemAsync`. After a lot of testing it looks like the view can´t be changed. After debugging I found out that the `ActivateItemAsync` value will be changed but the view just doesn´t change. I don´t even get a error or warning message. Is there a known Bug? 

I´ve created a more detailed post [here](https://stackoverflow.com/questions/68395940/caliburn-micro-navigation-from-usercontrol-over-shellviewmodel). A hint would be very nice.

**Comment by vb2ae** [comment]
Are you using .net framework, .net core, or .net 5.0 for the WPF?

**Comment by lgund** [comment]
Yes I am using .Net 5.

**Comment by lgund** [comment]
After some help from Stackoverflow I found out that I wasn´t on the correct instance. After changeing the bootstraper singleton it worked. Without help or a warning I couldn´t fix the problem. Maybe there should be added a warning?

**Comment by KasperSK** [comment]
I would try using an action message instead of injecting the `ShellVM` into the view. 
Like so: `<Button Content="Click Me" cal:Message.Attach="[Event Click] = [Action SayHello(Name.Text)]" />` 

The reason it works when `ShellVW` is a singleton, is that you don't get two instances of `ShellVW`.

Caliburn Micro sets the binding context for the `UserControl` so there should be no need to inject the `ShellVW` into the `UserControl`.

As for the warning I think that is a hard Caliburn Micro cannot guess about the intent of the user code.

**Comment by lgund** [comment]
Yea on normal redirection I would use the action but I need to translate also a full data object. I used the "A little Extended Implementation" from this [post](https://stackoverflow.com/questions/36899727/how-to-use-dependency-injection-with-conductors-in-caliburn-micro/51438993#51438993) here. It´s the simplest way to use it and it´s also better readable. Maybe we find a better solution in the feature here.
