### ISSUE TITLE
Loading Data in Lifecycle event

### ISSUE THREAD

**Issue by codinghavok** [Caliburn-Micro/Caliburn.Micro#773]
Hello,

I'm curious what the recommended method is for loading data in a view. Should this be done in the OnViewReady event or another event, or in the ViewModel constructor?

Example of what I have now that seems to work, but I want to make sure is the right location.

```
protected override void OnViewReady(object view)
        {
            LoadData();
            base.OnViewReady(view);
        }


```

**Comment by vb2ae** [comment]
In general the Screen's OnInitializeAsync event would be a good place to do this because you can load the data without blocking the UI from loading.

The OnViewReady event is called the first time the page's LayoutUpdated event fires after it is navigated to.  Using OnViewReady will load the data after the screen is loaded the first time.

**Comment by codinghavok** [comment]
@vb2ae Thank you. I appreciate it.
